TwoPlates Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/twoplates.h>
Public Member Functions
TwoPlates ()
TwoPlates (std::string, double, double, int, double, double)
~TwoPlates ()
void setSections (double)
void computeEnergy (double, std::vector< Particle * > &)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
double getLength ()
Additional Inherited Members
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
TwoPlates::TwoPlates ()
TwoPlates::TwoPlates (std::string type_in, double par1_in, double par2_in, int par3_in, double width_in, double orientation_in)
References Geometry::length.
TwoPlates::~TwoPlates ()
Member Function Documentation
void TwoPlates::computeEnergy (double section, std::vector< Particle * > & particles)
References Geometry::length, Geometry::sections, and Geometry::sectors.
void TwoPlates::computeGeometry () [virtual]
Implements Geometry.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void TwoPlates::computeIntersection (Particle * particle) [virtual]
Implements Geometry.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, and residue().
void TwoPlates::computeNodalPower (Particle * particle) [virtual]
Implements Geometry.
double TwoPlates::getLength () [inline]
References Geometry::length.
void TwoPlates::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
References Geometry::length, and Geometry::z0.
Referenced by computeIntersection().
void TwoPlates::outputPowerDensityFile () [virtual]
Implements Geometry.
References Geometry::elements, Geometry::nodes, and Geometry::sectors.
void TwoPlates::outputPowerFile (int particles) [virtual]
Implements Geometry.
References Geometry::elements, and Geometry::sectors.
void TwoPlates::outputTable () [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, and Geometry::sectors.
void TwoPlates::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
References Geometry::length, and Geometry::z0.
Referenced by computeIntersection().
void TwoPlates::setSections (double distance) [virtual]
Implements Geometry.
References Geometry::length, and Geometry::sections.
The documentation for this class was generated from the following files:
src/twoplates.h
src/twoplates.cpp