lmx::DiffProblemSecond< Sys, T > Class Template Reference
Template class DiffProblemSecond. Implementation for Fist Order ODE system solvers.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_diff_problem_second.h>
Public Member Functions
DiffProblemSecond ()
~DiffProblemSecond ()
void setResidue (void(Sys::*residue_in)(lmx::Vector< T > &residue, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time))
void setResidueByParts (void(Sys::*residue_q_qdot)(lmx::Vector< T > &res_q_qdot, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot), void(Sys::*residue_qddot)(lmx::Vector< T > &res_qddot, const lmx::Vector< T > &qddot), void(Sys::*residue_time)(lmx::Vector< T > &res_time, double time))
void setJacobian (void(Sys::*jacobian_in)(lmx::Matrix< T > &jacobian, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double partial_qdot, double partial_qddot, double time))
void setJacobianByParts (void(Sys::*jacobian_q_qdot)(lmx::Matrix< T > &jac_q_qdot, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double partial_qdot, double time), void(Sys::*jacobian_qddot)(lmx::Matrix< T > &jac_qddot, double partial_qddot, double time))
void setEvaluation (void(Sys::*eval_in)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, lmx::Vector< T > &qddot, double time))
void setIntegrator (int type, int opt1=0, int opt2=0)
void setIntegrator (const char *type, int opt2=0)
void setIntegrator (const char *type, double alpha_in)
void setIntegrator (const char *type, double beta, double gamma, double alpha=0)
void setConvergence (double eps_in)
void setConvergence (bool(Sys::*convergence)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time))
void setSparsePatternJacobian (lmx::DenseMatrix< T > &mat_sparse)
void iterationResidue (lmx::Vector< T > &residue, lmx::Vector< T > &delta_q)
void iterationResidueByParts (lmx::Vector< T > &residue, lmx::Vector< T > &delta_q)
void iterationResidueForAlpha (lmx::Vector< T > &residue, lmx::Vector< T > &delta_q)
void iterationJacobian (lmx::Matrix< T > &jacobian, lmx::Vector< T > &delta_q)
void iterationJacobianByParts (lmx::Matrix< T > &jacobian, lmx::Vector< T > &delta_q)
void iterationJacobianForAlpha (lmx::Matrix< T > &jacobian, lmx::Vector< T > &delta_q)
bool iterationConvergence (lmx::Vector< T > &delta_q)
void initialize ()
void solve ()
void stepSolve ()
Additional Inherited Members
Detailed Description
template<typename Sys, typename T = double>class lmx::DiffProblemSecond< Sys, T >
Template class DiffProblemSecond. Implementation for Fist Order ODE system solvers.
This class implements methods for defining and solving initial value problems described by a TotalDiff class' derivided object, and initial conditions in the form $ q(t_o) = q_o $.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename Sys , typename T = double> lmx::DiffProblemSecond< Sys, T >::DiffProblemSecond () [inline]
Empty constructor.
template<typename Sys , typename T = double> lmx::DiffProblemSecond< Sys, T >::~DiffProblemSecond () [inline]
Destructor.
References lmx::DiffProblem< Sys, T >::p_delta_q.
Member Function Documentation
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::initialize () [virtual]
Initialize solving function
Implements lmx::DiffProblem< Sys, T >.
template<typename Sys , typename T > bool lmx::DiffProblemSecond< Sys, T >::iterationConvergence (lmx::Vector< T > & delta_q)
Function for NLSolver convergence evaluation.
Parameters
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationJacobian (lmx::Matrix< T > & jacobian, lmx::Vector< T > & delta_q)
Function for NLSolver jacobian computation.
Parameters
jacobian Tangent matrix.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationJacobianByParts (lmx::Matrix< T > & jacobian, lmx::Vector< T > & delta_q)
Function for NLSolver jacobian computation. Used when ResidueByParts is set.
Parameters
jacobian Tangent matrix.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationJacobianForAlpha (lmx::Matrix< T > & jacobian, lmx::Vector< T > & delta_q)
Function for NLSolver jacobian computation. Used when ALPHA integrator is set.
Parameters
jacobian Tangent matrix.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationResidue (lmx::Vector< T > & residue, lmx::Vector< T > & delta_q)
Function for NLSolver residue computation.
Parameters
residue Residue vector.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationResidueByParts (lmx::Vector< T > & residue, lmx::Vector< T > & delta_q)
Function for NLSolver residue computation. Used when ResidueByParts is set.
Parameters
residue Residue vector.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::iterationResidueForAlpha (lmx::Vector< T > & residue, lmx::Vector< T > & delta_q)
Function for NLSolver residue computation. Used when ALPHA integrator is set.
Parameters
residue Residue vector.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T = double> void lmx::DiffProblemSecond< Sys, T >::setConvergence (double eps_in) [inline]
Backward resolution of mother function.
Parameters
L2 norm maximum residual.
References lmx::DiffProblem< Sys, T >::setConvergence().
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setConvergence (bool(Sys::*)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time) conv_in)
Sets the external function that implements a different convergence criteria from those available in LMX. Must be a Sys member function.
Parameters
conv_in The convergence evaluation function.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setEvaluation (void(Sys::*)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, lmx::Vector< T > &qddot, double time) eval_in)
Sets the external (first order configuration) evaluation function. Must be a Sys member function.
Parameters
eval_in The acceleration function.
template<typename Sys , typename T = double> void lmx::DiffProblemSecond< Sys, T >::setIntegrator (int type, int opt1 = 0, int opt2 = 0) [inline]
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator family to use.
opt1 Optional value for some integrators (usually specifies the order).
opt2 Optional value for some integrators.
References lmx::DiffProblem< Sys, T >::setIntegrator().
template<typename Sys , typename T = double> void lmx::DiffProblemSecond< Sys, T >::setIntegrator (const char * type, int opt2 = 0) [inline]
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator family to use.
opt2 Optional value for some integrators.
References lmx::DiffProblem< Sys, T >::setIntegrator().
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setIntegrator (const char * type, double alpha_in)
Defines the integrator that will be used for configuration advance & actualization (Alpha version).
Parameters
type Key of integrator family to use.
alpha_in HHT's alpha.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setIntegrator (const char * type, double beta_in, double gamma_in, double alpha_in = 0)
Defines the integrator that will be used for configuration advance & actualization (Newmark and Alpha version).
Parameters
type Key of integrator family to use.
beta_in Newmark's beta.
gamma_in Newmark's gamma.
alpha_in HHT's alpha.
std::pow(1+alpha,2)
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setJacobian (void(Sys::*)(lmx::Matrix< T > &jacobian, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double partial_qdot, double partial_qddot, double time) jacobian_in)
Sets the external function for tangent to q. Must be a Sys member function. ::: change documentation :::
Parameters
jacobian_in Tangent function.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setJacobianByParts (void(Sys::*)(lmx::Matrix< T > &jac_q_qdot, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double partial_qdot, double time) jacobian_q_qdot, void(Sys::*)(lmx::Matrix< T > &jac_qddot, double partial_qddot, double time) jacobian_qddot)
Sets the external function for residue evaluation. Must be a Sys member function. ::: change documentation :::
Parameters
jacobian_q_qdot Tangent member function depending on $ q $ and $ \frac{dq}{dt} $ .
jacobian_qddot Tangent member function depending on $ \frac{d^2q}{dt^2} $ .
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setResidue (void(Sys::*)(lmx::Vector< T > &residue, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time) residue_in)
Sets the external function for residue evaluation. Must be a Sys member function.
Parameters
residue_in Residue function.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::setResidueByParts (void(Sys::*)(lmx::Vector< T > &res_q_qdot, const lmx::Vector< T > &q, const lmx::Vector< T > &qdot) residue_q_qdot, void(Sys::*)(lmx::Vector< T > &res_qddot, const lmx::Vector< T > &qddot) residue_qddot, void(Sys::*)(lmx::Vector< T > &res_time, double time) residue_time)
Sets the external function for residue evaluation. Must be a Sys member function.
Parameters
residue_q_qdot Residue member function depending on $ q $ and $ \frac{dq}{dt} $ .
residue_qddot Residue member function depending on $ \frac{d^2q}{dt^2} $ .
residue_time Residue member function depending on time, $ t $ .
template<typename Sys , typename T = double> void lmx::DiffProblemSecond< Sys, T >::setSparsePatternJacobian (lmx::DenseMatrix< T > & mat_sparse) [inline]
References lmx::DenseMatrix< T >::writeSparsePattern().
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::solve () [virtual]
Solve main function
Implements lmx::DiffProblem< Sys, T >.
template<typename Sys , typename T > void lmx::DiffProblemSecond< Sys, T >::stepSolve () [virtual]
Solve only one step
Implements lmx::DiffProblem< Sys, T >.
The documentation for this class was generated from the following file:
src/LMX/lmx_diff_problem_second.h