lmx::DenseMatrix< T > Class Template Reference
Template class DenseMatrix.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_dense_matrix.h>
Public Member Functions
DenseMatrix ()
DenseMatrix (size_type, size_type)
DenseMatrix (const DenseMatrix &)
~DenseMatrix ()
DenseMatrix & mult (const Matrix< T > &, const Matrix< T > &)
DenseMatrix & operator= (const Matrix< T > &)
DenseMatrix & multElements (const Matrix< T > &)
DenseMatrix & multElements (const Matrix< T > &, const Matrix< T > &)
DenseMatrix operator+ (const Matrix< T > &B) const
DenseMatrix operator- (const Matrix< T > &B) const
DenseMatrix< T > operator* (const Matrix< T > &B) const
const T & readElement (size_type m, size_type n) const
void writeElement (T theValue, size_type m, size_type n) const
void addElement (const T theValue, size_type m, size_type n) const
void writeSparsePattern (std::vector< size_type > &, std::vector< size_type > &) const
Detailed Description
template<typename T>class lmx::DenseMatrix< T >
Template class DenseMatrix.
This class allows the creation of dense matrix objects. A DenseMatrix object owns two parameters, nrows and mcolumns, that store the dimension of the matrix container. The data is stored in an atribute (*type_matrix) that points to some class which derives from the Data_mat class.
Parameters
mrows The number of rows of the Data Container (Data_mat).
ncolumns The number of columns of the Data Container (Data_mat).
reference An Elem_ref object for r/w data access.
*type_matrix The pointer to the matrix data container.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T > lmx::DenseMatrix< T >::DenseMatrix ()
Empty constructor.
template<typename T > lmx::DenseMatrix< T >::DenseMatrix (size_type rows, size_type columns)
Standard constructor.
Parameters
rows Number of rows in DenseMatrix.
columns Number of columns in DenseMatrix.
template<typename T > lmx::DenseMatrix< T >::DenseMatrix (const DenseMatrix< T > & A)
Copy constructor.
Parameters
A DenseMatrix to copy from.
template<typename T > lmx::DenseMatrix< T >::~DenseMatrix ()
Destructor.
Member Function Documentation
template<typename T> void lmx::DenseMatrix< T >::addElement (const T theValue, size_type m, size_type n) const [inline]
Function adds the value in specified position of Matrix object.
template<typename T> DenseMatrix< T > & lmx::DenseMatrix< T >::mult (const Matrix< T > & A, const Matrix< T > & B) [inline]
Matrix objects multiplication, with result storing in the DenseMatrix object.
Parameters
A Left Matrix.
B Right Matrix.
Returns
Reference to multiplication result in DenseMatrix.
References lmx::mat_mat_mult().
template<typename T> DenseMatrix< T > & lmx::DenseMatrix< T >::multElements (const Matrix< T > & B) [inline]
Internal product between matrices. Multiplies each element of object to its equivalent in Matrix B.
Parameters
B Matrix to multiply to.
Returns
Reference to internal product result.
References lmx::mat_mat_multElements().
template<typename T> DenseMatrix< T > & lmx::DenseMatrix< T >::multElements (const Matrix< T > & A, const Matrix< T > & B) [inline]
Internal product between two Matrix objects. Multiplies each element in Matrix A to its equivalent in Matrix B and saves the result in object from whitch the function is invoked.
Parameters
A Matrix to multiply.
B Matrix to multiply.
Returns
Reference to internal product result.
References lmx::mat_mat_multElements().
template<typename T> DenseMatrix<T> lmx::DenseMatrix< T >::operator* (const Matrix< T > & B) const [inline]
Overloaded operator for multiplying DenseMatrix and Matrix objects.
template<typename T> DenseMatrix lmx::DenseMatrix< T >::operator+ (const Matrix< T > & B) const [inline]
Overloaded operator for adding elements between a DenseMatrix and a Matrix object.
template<typename T> DenseMatrix lmx::DenseMatrix< T >::operator- (const Matrix< T > & B) const [inline]
Overloaded operator for adding elements between a DenseMatrix and a Matrix object.
template<typename T> DenseMatrix< T > & lmx::DenseMatrix< T >::operator= (const Matrix< T > & A) [inline]
Overloaded operator for equaling every element between a DenseMatrix and a Matrix object of the same type.
Parameters
A Matrix to be equal to.
template<typename T> const T& lmx::DenseMatrix< T >::readElement (size_type m, size_type n) const [inline]
Function that returns the value in specified position of Matrix object.
Referenced by lmx::Vector< T >::mult(), and lmx::DenseMatrix< double >::operator*().
template<typename T> void lmx::DenseMatrix< T >::writeElement (T theValue, size_type m, size_type n) const [inline]
Function writes the value in specified position of Matrix object.
Referenced by lmx::DenseMatrix< double >::operator*().
template<typename T > void lmx::DenseMatrix< T >::writeSparsePattern (std::vector< size_type > & nRows, std::vector< size_type > & nCols) const
Writes in two STL vectors the HB column and row indexes of the Non-zeros.
Referenced by lmx::DiffProblemSecond< Sys, T >::setSparsePatternJacobian(), lmx::DiffProblemFirstSecond< Sys, T >::setSparsePatternJacobian1(), and lmx::DiffProblemFirstSecond< Sys, T >::setSparsePatternJacobian2().
The documentation for this class was generated from the following file:
src/LMX/lmx_mat_dense_matrix.h