lmx::LinearSystem< T > Class Template Reference
Template class LinearSystem. Linear systems implementation: `A*x = b` .
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_linsolvers_system.h>
Public Member Functions
LinearSystem ()
LinearSystem (Matrix< T > &A_in, Vector< T > &b_in)
LinearSystem (DenseMatrix< T > &dA_in, Vector< T > &b_in)
template<class C >
LinearSystem (Matrix< C > &A_in, Vector< C > &b_in)
LinearSystem (Matrix< T > &A_in, Vector< T > &x_in, Vector< T > &b_in)
LinearSystem (DenseMatrix< T > &dA_in, Vector< T > &x_in, Vector< T > &b_in)
template<class C >
LinearSystem (Matrix< C > &A_in, Vector< T > &x_in, Vector< C > &b_in)
LinearSystem (DenseMatrix< T > &A_in, DenseMatrix< T > &B_in)
LinearSystem (Matrix< T > &A_in, DenseMatrix< T > &B_in)
LinearSystem (DenseMatrix< T > &A_in, Matrix< T > &B_in)
LinearSystem (Matrix< T > &A_in, Matrix< T > &B_in)
~LinearSystem ()
void setInfo (int level)
void initSLU ()
void solve (int recalc=0)
Solve function.
void solveYourselfMatrix (int recalc=0)
Vector< T > & solveYourself (int recalc=0)
void factorize ()
void subsSolve ()
Vector< T > & getSolution ()
Vector< T > & getSolutionVector ()
Matrix< T > & getSolutionMatrix ()
void setb (Vector< T > &b_in)
void setA (Matrix< T > &A_in)
Detailed Description
template<class T>class lmx::LinearSystem< T >
Template class LinearSystem. Linear systems implementation: `A*x = b` .
This class permits the creation of a linear system object. Each object has three parameters, corresponding to each of the matrices or vectors base of the problem. The basic methods solve the problem and add functionality to control the solution procedure. Not only one solver can be used as well as the number data type (class) may be differ between the input and the one used to solve the system.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<class T> lmx::LinearSystem< T >::LinearSystem () [inline]
Empty constructor.
template<class T> lmx::LinearSystem< T >::LinearSystem (Matrix< T > & A_in, Vector< T > & b_in) [inline]
Standard constructor with two parameters.
Parameters
A_in LHS Matrix.
b_in RHS Vector.
template<class T> lmx::LinearSystem< T >::LinearSystem (DenseMatrix< T > & dA_in, Vector< T > & b_in) [inline]
Standard constructor with two parameters (DenseMatrix).
Parameters
dA_in LHS DenseMatrix.
b_in RHS Vector.
template<class T> template<class C > lmx::LinearSystem< T >::LinearSystem (Matrix< C > & A_in, Vector< C > & b_in) [inline]
Standard constructor with two parameters with different data type as that of LinearSystem.
Parameters
A_in LHS Matrix.
b_in RHS Vector.
template<class T> lmx::LinearSystem< T >::LinearSystem (Matrix< T > & A_in, Vector< T > & x_in, Vector< T > & b_in) [inline]
Standard constructor with three parameters.
Parameters
A_in LHS Matrix.
x_in Solution vector.
b_in RHS Vector.
Returns
template<class T> lmx::LinearSystem< T >::LinearSystem (DenseMatrix< T > & dA_in, Vector< T > & x_in, Vector< T > & b_in) [inline]
Standard constructor with three parameters (DenseMatrix).
Parameters
dA_in LHS DenseMatrix.
x_in Solution vector.
b_in RHS Vector.
template<class T> template<class C > lmx::LinearSystem< T >::LinearSystem (Matrix< C > & A_in, Vector< T > & x_in, Vector< C > & b_in) [inline]
Standard constructor with three parameters, two of them with different data types.
Parameters
A_in LHS Matrix.
x_in Solution vector.
b_in RHS Vector.
Returns
template<class T> lmx::LinearSystem< T >::LinearSystem (DenseMatrix< T > & A_in, DenseMatrix< T > & B_in) [inline]
Standard constructor for nrhs system (Matrix).
Parameters
dA_in LHS DenseMatrix.
b_in RHS Vector.
template<class T> lmx::LinearSystem< T >::LinearSystem (Matrix< T > & A_in, DenseMatrix< T > & B_in) [inline]
template<class T> lmx::LinearSystem< T >::LinearSystem (DenseMatrix< T > & A_in, Matrix< T > & B_in) [inline]
template<class T> lmx::LinearSystem< T >::LinearSystem (Matrix< T > & A_in, Matrix< T > & B_in) [inline]
template<class T> lmx::LinearSystem< T >::~LinearSystem () [inline]
Destructor.
Member Function Documentation
template<class T > void LinearSystem< T >::factorize (void)
References lmx::getMatrixType().
template<class T> Vector<T>& lmx::LinearSystem< T >::getSolution () [inline]
Solution access (DEPRECATED).
Returns
A vector with solution values.
template<class T> Matrix<T>& lmx::LinearSystem< T >::getSolutionMatrix () [inline]
Solution access for matrix n-rhs.
Returns
a matrix with solution values.
template<class T> Vector<T>& lmx::LinearSystem< T >::getSolutionVector () [inline]
Solution access for vector 1-rhs.
Returns
A vector with solution values.
template<class T > void LinearSystem< T >::initSLU ()
References lmx::Type_stdVector< T >::data_pointer().
Referenced by lmx::LinearSystem< double >::LinearSystem().
template<class T> void LinearSystem< T >::setA (Matrix< T > & A_in)
References lmx::getMatrixType().
template<class T> void LinearSystem< T >::setb (Vector< T > & b_in)
References lmx::Type_stdVector< T >::data_pointer(), and lmx::getMatrixType().
template<class T> void lmx::LinearSystem< T >::setInfo (int level) [inline]
Set information level.
template<class T > void LinearSystem< T >::solve (int recalc = 0)
Solve function.
Depending on Matrix and lin_solver types selected, the following combinations are possible:
getLinSolverType() getMatrixType() Solver used:
0 0 LU
0 1 SuperLU
0 2 gmm::lu_solve (SuperLU in the future)
0 3 gmm::lu_solve (SuperLU in the future)
1 0 LU
1 1 SuperLU
1 2 gmm::lu_solve (SuperLU in the future)
1 3 gmm::lu_solve (SuperLU in the future)
2 0 lmx::Cg
2 1 lmx::Cg
2 2 lmx::Cg (and gmm::cg possible if uncommented)
2 3 lmx::Cg (and gmm::cg possible if uncommented)
3 0 -
3 1 -
3 2 -
3 3 gmm::gmres
IMPORTANT: gmm::lu_solve is not implemented when the vector_type is set to code 1 (Type_gmmVector_sparse). To Be Done.
When a solver is not available, an error will be thrown.
Parameters
recalc For SuperLU switches between refactoring (FALSE) or use old factoring (TRUE).
Returns
reference of solution Vector.
template<class T > Vector< T > & LinearSystem< T >::solveYourself (int recalc = 0)
References lmx::Type_gmm< T >::data_pointer(), lmx::Type_gmmVector_sparse< T >::data_pointer(), lmx::Type_gmm_sparse< T >::data_pointer(), lmx::Type_stdVector< T >::data_pointer(), lmx::getLinSolverType(), lmx::getMatrixType(), lmx::getVectorType(), LMX_THROW, lmx::Cg< T >::precond(), lmx::Cg< T >::solve(), lmx::LU< T >::solve(), and lmx::Gesv< T >::solve().
Referenced by lmx::NLSolver< Sys, T >::solve(), lmx::NLSolverDouble< Sys, T >::solve(), and lmx::solveLinear().
template<class T > void LinearSystem< T >::solveYourselfMatrix (int recalc = 0)
References LMX_THROW, and lmx::LU< T >::solve_nrhs().
template<class T > void LinearSystem< T >::subsSolve (void)
References lmx::Type_stdVector< T >::data_pointer(), and lmx::getMatrixType().
The documentation for this class was generated from the following file:
src/LMX/lmx_linsolvers_system.h