lmx::Data< T > Class Template Reference
Template class Data. Mother class for Data_mat & Data_vec.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_data.h>
Public Member Functions
Data ()
virtual ~Data ()
virtual void resize (size_type, size_type)=0
virtual const T & readElement (const size_type &, const size_type &) const =0
virtual void writeElement (T, const size_type &, const size_type &)=0
virtual void addElement (T, const size_type &, const size_type &)=0
virtual size_type getRows () const =0
virtual size_type getCols () const =0
virtual void equals (const Data *)=0
virtual void add (const Data *)=0
virtual void substract (const Data *)=0
virtual void multiplyScalar (const T &)=0
virtual void multiplyElements (const Data *)=0
virtual void cleanBelow (const double)=0
virtual void clear ()=0
virtual void reset ()=0
Detailed Description
template<typename T>class lmx::Data< T >
Template class Data. Mother class for Data_mat & Data_vec.
This class represents the skeleton for the data container used by the Vector and Matrix classes. No parameter nor function implementation here, just pure virtual class. See derived classes for details in implementation. Also maybe useful to see how this class is used in the Vector class.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename T> lmx::Data< T >::Data () [inline]
Empty constructor.
template<typename T> virtual lmx::Data< T >::~Data () [inline], [virtual]
Destructor.
Member Function Documentation
template<typename T> virtual void lmx::Data< T >::add (const Data< T > *) [pure virtual]
Method for adding object's data to the parameter's data. Necessary for implementing the `+=` overloaded operator method in Vector and Vector class types.
Implemented in lmx::Type_stdVector< T >, lmx::Type_stdmatrix< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::addElement (T , const size_type & , const size_type &) [pure virtual]
Write method for adding to data.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::cleanBelow (const double) [pure virtual]
Method for cleaning all elements below a given factor.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::clear () [pure virtual]
Method for clearing all elements.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::equals (const Data< T > *) [pure virtual]
Method for equaling object's data to the parameter's data. Necessary for implementing the `=` overloaded operator method in Vector and Vector class types.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual size_type lmx::Data< T >::getCols () const [pure virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
Referenced by lmx::mat_mat_add(), lmx::mat_mat_mult(), lmx::mat_mat_multElements(), lmx::mat_mat_subs(), lmx::Type_csc< T >::multiply(), and lmx::Type_stdmatrix< double >::multiply().
template<typename T> virtual size_type lmx::Data< T >::getRows () const [pure virtual]
Method for knowing the number of data rows.
Returns
Number of rows.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
Referenced by lmx::mat_mat_add(), lmx::mat_mat_mult(), lmx::mat_mat_multElements(), lmx::mat_mat_subs(), lmx::Type_csc< T >::multiply(), and lmx::Type_stdmatrix< double >::multiply().
template<typename T> virtual void lmx::Data< T >::multiplyElements (const Data< T > *) [pure virtual]
Method multiplying element-by-element of two arrays. One would be the object's contents and the other the parameter's contents. Necessary for implementing Vector to Vector multElements.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdVector< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, lmx::Type_gmmVector_sparse< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::multiplyScalar (const T &) [pure virtual]
Method for multiplying a scalar with an array and saving the result in the object's data. Necessary for implementing the `*` overloaded operator method with scalars in Vector class type.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, lmx::Type_gmmVector_sparse< T >, and lmx::Type_csc< T >.
template<typename T> virtual const T& lmx::Data< T >::readElement (const size_type & , const size_type &) const [pure virtual]
Read method for accesing stored data.
Returns
Value of the data stored in the (size_type,size_type) position.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_csc< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, and lmx::Type_gmm< T >.
Referenced by lmx::Type_csc< T >::add(), lmx::Type_stdmatrix< double >::add(), lmx::mat_mat_add(), lmx::mat_mat_mult(), lmx::mat_mat_multElements(), lmx::mat_mat_subs(), lmx::Type_csc< T >::multiply(), lmx::Type_stdmatrix< double >::multiply(), lmx::Type_csc< T >::multiplyElements(), lmx::Type_gmmVector_sparse< T >::multiplyElements(), lmx::Type_gmm< T >::multiplyElements(), lmx::Type_gmm_sparse< T >::multiplyElements(), lmx::Type_stdVector< T >::multiplyElements(), lmx::Type_stdmatrix< double >::multiplyElements(), lmx::Type_csc< T >::substract(), and lmx::Type_stdmatrix< double >::substract().
template<typename T> virtual void lmx::Data< T >::reset () [pure virtual]
Method for all elements to 0
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::resize (size_type , size_type) [pure virtual]
Resize method for augmenting or reducing the container's dimension.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_csc< T >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, and lmx::Type_gmm< T >.
Referenced by lmx::mat_mat_mult().
template<typename T> virtual void lmx::Data< T >::substract (const Data< T > *) [pure virtual]
Method for substracting object's data from the parameter's data. Necessary for implementing the `-=` overloaded operator method in Vector and Vector class types.
Implemented in lmx::Type_stdVector< T >, lmx::Type_stdmatrix< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_gmm< T >, and lmx::Type_csc< T >.
template<typename T> virtual void lmx::Data< T >::writeElement (T , const size_type & , const size_type &) [pure virtual]
Write method for storing data.
Implemented in lmx::Type_stdmatrix< T >, lmx::Type_stdmatrix< double >, lmx::Type_stdVector< T >, lmx::Type_gmmVector_sparse< T >, lmx::Type_gmm_sparse< T >, lmx::Type_csc< T >, and lmx::Type_gmm< T >.
Referenced by lmx::mat_mat_add(), lmx::mat_mat_mult(), lmx::mat_mat_multElements(), and lmx::mat_mat_subs().
The documentation for this class was generated from the following file:
src/LMX/lmx_mat_data.h