cofe::TensorRank2Sym< Dim, T > Class Template Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/cofe_TensorRank2Sym.h>
Public Member Functions
TensorRank2Sym ()
TensorRank2Sym (const T ptr[Dim][Dim])
TensorRank2Sym (const T &aValue)
TensorRank2Sym (const TensorRank2Sym< Dim, T > &aTen)
virtual ~TensorRank2Sym ()
void operator= (const T &aValue)
TensorRank2Sym< Dim, T > & operator= (const TensorRank2Sym< Dim, T > &aTen)
virtual void beSymmetricPartOf (const cofe::TensorRank2< Dim, T > &r2T)
virtual void beHydrostaticPartOf (const cofe::TensorRank2Sym< Dim, T > &r2T)
virtual void beDeviatoricPartOf (const cofe::TensorRank2Sym< Dim, T > &r2T)
void beProductOf (const cofe::AbstractTensorRank4SS< Dim, T > &r4T, const cofe::TensorRank2Sym< Dim, T > &r2ST)
void beSymProductOf (const cofe::TensorRank1< Dim, T > &lv, const cofe::TensorRank1< Dim, T > &rv)
bool checkSymmetry ()
double maxPrincipalValue () const
void computeMaxPrincipalDirection (TensorRank1< Dim, T > &) const
template<>
double maxPrincipalValue () const
template<>
double maxPrincipalValue () const
template<>
void computeMaxPrincipalDirection (TensorRank1< 2, double > &prdir) const
template<>
void computeMaxPrincipalDirection (TensorRank1< 3, double > &prdir) const
Protected Member Functions
int index (int i, int j) const
Additional Inherited Members
Constructor & Destructor Documentation
template<int Dim, class T = double> cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym () [inline]
template<int Dim, class T = double> cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym (const T ptr[Dim][Dim]) [inline]
References cofe::TensorRank2Sym< Dim, T >::checkSymmetry().
template<int Dim, class T = double> cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym (const T & aValue) [inline]
template<int Dim, class T = double> cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym (const TensorRank2Sym< Dim, T > & aTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T = double> virtual cofe::TensorRank2Sym< Dim, T >::~TensorRank2Sym () [inline], [virtual]
Member Function Documentation
template<int Dim, class T = double> virtual void cofe::TensorRank2Sym< Dim, T >::beDeviatoricPartOf (const cofe::TensorRank2Sym< Dim, T > & r2T) [inline], [virtual]
References cofe::TensorRank2Sym< Dim, T >::beHydrostaticPartOf().
template<int Dim, class T = double> virtual void cofe::TensorRank2Sym< Dim, T >::beHydrostaticPartOf (const cofe::TensorRank2Sym< Dim, T > & r2T) [inline], [virtual]
References cofe::TensorRank2< Dim, T >::beUnityTensor(), and cofe::TensorRank2< Dim, T >::trace().
Referenced by cofe::TensorRank2Sym< Dim, T >::beDeviatoricPartOf().
template<int Dim, class T = double> void cofe::TensorRank2Sym< Dim, T >::beProductOf (const cofe::AbstractTensorRank4SS< Dim, T > & r4T, const cofe::TensorRank2Sym< Dim, T > & r2ST) [inline]
template<int Dim, class T = double> virtual void cofe::TensorRank2Sym< Dim, T >::beSymmetricPartOf (const cofe::TensorRank2< Dim, T > & r2T) [inline], [virtual]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T = double> void cofe::TensorRank2Sym< Dim, T >::beSymProductOf (const cofe::TensorRank1< Dim, T > & lv, const cofe::TensorRank1< Dim, T > & rv) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T = double> bool cofe::TensorRank2Sym< Dim, T >::checkSymmetry () [inline]
References cofe::TensorRank2< Dim, T >::com.
Referenced by cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym().
template<int Dim, class T > void cofe::TensorRank2Sym< Dim, T >::computeMaxPrincipalDirection (TensorRank1< Dim, T > &) const [inline]
template<> void cofe::TensorRank2Sym< 2, double >::computeMaxPrincipalDirection (TensorRank1< 2, double > & prdir) const [inline]
template<> void cofe::TensorRank2Sym< 3, double >::computeMaxPrincipalDirection (TensorRank1< 3, double > & prdir) const [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T = double> int cofe::TensorRank2Sym< Dim, T >::index (int i, int j) const [inline], [protected]
template<int Dim, class T > double cofe::TensorRank2Sym< Dim, T >::maxPrincipalValue () const [inline]
template<> double cofe::TensorRank2Sym< 3, double >::maxPrincipalValue () const [inline]
template<> double cofe::TensorRank2Sym< 2, double >::maxPrincipalValue () const [inline]
template<int Dim, class T = double> void cofe::TensorRank2Sym< Dim, T >::operator= (const T & aValue) [inline]
References cofe::TensorRank2< Dim, T >::operator=().
template<int Dim, class T = double> TensorRank2Sym<Dim,T>& cofe::TensorRank2Sym< Dim, T >::operator= (const TensorRank2Sym< Dim, T > & aTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
The documentation for this class was generated from the following file:
src/LMX/cofe_TensorRank2Sym.h