lmx::Gesv< T > Class Template Reference
Template class for lapack ?gesv routine.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_linsolvers_lapack.h>
Public Member Functions
Gesv ()
Gesv (Matrix< T > *, Vector< T > *, Vector< T > *)
~Gesv ()
void solve ()
template<>
void solve ()
Detailed Description
template<typename T>class lmx::Gesv< T >
Template class for lapack ?gesv routine.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T> lmx::Gesv< T >::Gesv () [inline]
Empty constructor.
template<typename T > lmx::Gesv< T >::Gesv (Matrix< T > * a_in, Vector< T > * x_in, Vector< T > * b_in)
Standard constructor.
Parameters
a_in Pointer to Matrix.
x_in Pointer to solution Vector.
b_in Pointer to rhs Vector.
References LMX_THROW, and lmx::Vector< T >::readElement().
template<typename T > lmx::Gesv< T >::~Gesv ()
Destructor
Member Function Documentation
template<typename T > void lmx::Gesv< T >::solve ()
Solve system
Returns
Reference to solution vector.
References LMX_THROW.
Referenced by lmx::LinearSystem< T >::solveYourself().
template<> void lmx::Gesv< double >::solve () [inline]
Solve system, specialized for double data type.
Returns
Reference to solution vector.
References dgesv_().
The documentation for this class was generated from the following file:
src/LMX/lmx_linsolvers_lapack.h