Ogive Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/ogive.h>
Public Member Functions
Ogive ()
Ogive (std::string, double, double, double, int, double)
~Ogive ()
void setSections (double)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
Additional Inherited Members
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Ogive::Ogive ()
Ogive::Ogive (std::string type_in, double par0_in, double par1_in, double par2_in, int par3_in, double par4_in)
References Geometry::gridWidth, and Geometry::length.
Ogive::~Ogive ()
Member Function Documentation
void Ogive::computeGeometry () [virtual]
Implements Geometry.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ogive::computeIntersection (Particle * particle) [virtual]
Implements Geometry.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, residue(), and Geometry::z0.
void Ogive::computeNodalPower (Particle * particle) [virtual]
Implements Geometry.
References Particle::getEnergy(), Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Geometry::length, Geometry::nodes, Geometry::paramTrajectories, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ogive::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
References Geometry::z0.
Referenced by computeIntersection().
void Ogive::outputPowerDensityFile () [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ogive::outputPowerFile (int particles) [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void Ogive::outputTable () [virtual]
Implements Geometry.
void Ogive::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
References Geometry::z0.
Referenced by computeIntersection().
void Ogive::setSections (double distance) [virtual]
Implements Geometry.
References Geometry::length, and Geometry::sections.
The documentation for this class was generated from the following files:
src/ogive.h
src/ogive.cpp