Matrix< T > Class Template Reference
Template class Matrix.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_matrix.h>
Public Member Functions
Matrix ()
Matrix (size_type, size_type)
Matrix (const Matrix &)
Matrix (const DenseMatrix< T > &)
~Matrix ()
void initialize_type_matrix (int)
size_type rows () const
size_type cols () const
void matrixMarketLoad (char *)
void harwellBoeingLoad (char *)
void harwellBoeingSave (char *)
void fillIdentity (T factor=static_cast< T >(1))
void fillRandom (T factor=static_cast< T >(1))
void sparsePattern (Vector< size_type > &, Vector< size_type > &)
void sparsePattern (std::vector< size_type > &, std::vector< size_type > &)
void sparsePattern (DenseMatrix< T > &)
Elem_ref< T > operator() (size_type, size_type)
Matrix & operator= (const Matrix &)
template<typename C >
Matrix< T > & operator= (const Matrix< C > &)
Matrix & operator= (const DenseMatrix< T > &)
Matrix & operator+= (const Matrix &)
Matrix & operator+= (const DenseMatrix< T > &)
Matrix & operator-= (const Matrix &)
Matrix & operator-= (const DenseMatrix< T > &)
Matrix & operator*= (T)
Matrix & operator/= (T)
Matrix & add (const Matrix &A, const Matrix &B)
Matrix & add (const Matrix &A, const DenseMatrix< T > &B)
Matrix & add (const DenseMatrix< T > &A, const Matrix &B)
Matrix & subs (const Matrix &A, const Matrix &B)
Matrix & subs (const Matrix &A, const DenseMatrix< T > &B)
Matrix & subs (const DenseMatrix< T > &A, const Matrix &B)
Matrix & mult (const Matrix &A, const Matrix &B)
Matrix & mult (const Matrix &A, const DenseMatrix< T > &B)
Matrix & mult (const DenseMatrix< T > &A, const Matrix &B)
Matrix & mult (const DenseMatrix< T > &A, const DenseMatrix< T > &B)
Matrix & multElements (const Matrix &)
Matrix & multElements (const DenseMatrix< T > &)
Matrix & multElements (const Matrix< T > &, const Matrix< T > &)
Matrix & multElements (const Matrix< T > &, const DenseMatrix< T > &)
Matrix & multElements (const DenseMatrix< T > &, const Matrix< T > &)
Matrix & multElements (const DenseMatrix< T > &, const DenseMatrix< T > &)
const T & readElement (size_type m, size_type n) const
void writeElement (T theValue, size_type m, size_type n) const
void addElement (const T theValue, size_type m, size_type n) const
void clean (T factor)
void clear ()
void reset ()
void resize (size_type i, size_type j)
void resize (const Matrix &mat)
Matrix & transpose ()
Matrix operator+ (const Matrix< T > &B) const
Matrix operator+ (const DenseMatrix< T > &B) const
Matrix< T > operator- (const Matrix< T > &B) const
Matrix operator- (const DenseMatrix< T > &B) const
Matrix< T > operator* (const Matrix< T > &B) const
Matrix< T > operator* (const DenseMatrix< T > &B) const
Matrix< T > operator* (const T &scalar) const
bool exists (size_type row, size_type col)
bool checkSymmetry ()
void factorize ()
void subsSolve (Vector< T > &rhs)
template<typename T >
Matrix< T > & operator= (const Matrix< T > &A)
template<typename C >
Matrix< T > & operator= (const Matrix< C > &A)
template<typename T >
Matrix< T > & operator= (const DenseMatrix< T > &A)
Protected Member Functions
Matrix (int)
Matrix (size_type, size_type, int)
Protected Attributes
size_type mrows
size_type ncolumns
Elem_ref< T > * reference
Data_mat< T > * type_matrix
Friends
class Vector< T >
class DenseMatrix< T >
class LinearSystem< T >
class LMXTester
Matrix transposed (const Matrix &mat_in)
template<typename C >
void lmx::latexPrint (std::ofstream &os, char *mat_name, Matrix< C > &mat, int prec)
Detailed Description
template<typename T>class Matrix< T >
Template class Matrix.
This class permits the creation of matrix objects. A Matrix object owns two parameters, nrows and mcolumns, that store the dimension of the matrix container. The data is stored in an atribute (*type_matrix) that points to some class which derives from the Data_mat class.
Parameters
mrows The number of rows of the Data Container (Data_mat).
ncolumns The number of columns of the Data Container (Data_mat).
reference An Elem_ref object for r/w data access.
*type_matrix The pointer to the matrix data container.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename T> Matrix< T >::Matrix (int) [protected]
template<typename T> Matrix< T >::Matrix (size_type , size_type , int) [protected]
template<typename T> Matrix< T >::Matrix ()
Empty constructor.
References getMatrixType(), and Matrix< T >::initialize_type_matrix().
template<typename T> Matrix< T >::Matrix (size_type , size_type)
template<typename T> Matrix< T >::Matrix (const Matrix< T > &)
template<typename T> Matrix< T >::Matrix (const DenseMatrix< T > &)
template<typename T> Matrix< T >::~Matrix ()
Destructor.
Member Function Documentation
template<typename T> Matrix& Matrix< T >::add (const Matrix< T > & A, const Matrix< T > & B) [inline]
template<typename T> Matrix& Matrix< T >::add (const Matrix< T > & A, const DenseMatrix< T > & B) [inline]
template<typename T> Matrix& Matrix< T >::add (const DenseMatrix< T > & A, const Matrix< T > & B) [inline]
template<typename T> void Matrix< T >::addElement (const T theValue, size_type m, size_type n) const [inline]
Function adds the value in specified position of Matrix object.
template<typename T> bool Matrix< T >::checkSymmetry () [inline]
Retuns 1 if the Matrix is symmetric and 0 if it does not. Needs documentation!
template<typename T> void Matrix< T >::clean (T factor) [inline]
Cleans all numbers below given factor.
template<typename T> void Matrix< T >::clear () [inline]
Clears the object's contents.
template<typename T> size_type Matrix< T >::cols () const [inline]
Read number of cols.
Returns
Number of cols of matrix.
Referenced by Matrix< T >::operator*(), Matrix< T >::operator=(), and Matrix< T >::resize().
template<typename T> bool Matrix< T >::exists (size_type row, size_type col) [inline]
Retuns 1 if the element exists inside the storing structure and 0 if it does not.
template<typename T> void Matrix< T >::factorize (void) [inline]
DOCUMENT
template<typename T> void Matrix< T >::fillIdentity (T factor = static_cast<T>(1))
Cleans matrix and sets diagonal terms to specified value. Matrix must be square.
Parameters
factor Value of diagonal terms. Default is one.
References LMX_THROW.
template<typename T> void Matrix< T >::fillRandom (T factor = static_cast<T>(1))
Function for filling a matrix with random numbers
Parameters
factor Scales the random numbers (default value is unity).
template<typename T> void Matrix< T >::harwellBoeingLoad (char * input_file)
Method for reading a matrix in Harwell-Boeing format from a file.
Parameters
input_file Name of the file to read.
template<typename T> void Matrix< T >::harwellBoeingSave (char * input_file)
Method for reading a matrix in Harwell-Boeing format from a file.
Parameters
input_file Name of the file to read.
template<typename T> void Matrix< T >::initialize_type_matrix (int type) [inline]
Function that creates specified matrix and a new Elem_ref with it.
Parameters
type Integer with matrix type identifier.
References LMX_THROW.
Referenced by Matrix< T >::Matrix().
template<typename T> void Matrix< T >::matrixMarketLoad (char * input_file)
Method for reading a matrix in Matrix-Market format from a file.
Parameters
input_file Name of the file to read.
template<typename T> Matrix& Matrix< T >::mult (const Matrix< T > & A, const Matrix< T > & B) [inline]
Referenced by Matrix< T >::operator*().
template<typename T> Matrix& Matrix< T >::mult (const Matrix< T > & A, const DenseMatrix< T > & B) [inline]
template<typename T> Matrix& Matrix< T >::mult (const DenseMatrix< T > & A, const Matrix< T > & B) [inline]
template<typename T> Matrix< T > & Matrix< T >::mult (const DenseMatrix< T > & A, const DenseMatrix< T > & B) [inline]
DenseMatrix objects multiplication, with result storing in the Matrix object.
Parameters
A Left DenseMatrix.
B Right DenseMatrix.
Returns
Reference to multiplication result in Matrix.
References lmx::mat_mat_mult().
template<typename T> Matrix& Matrix< T >::multElements (const Matrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::multElements (const DenseMatrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::multElements (const Matrix< T > & , const Matrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::multElements (const Matrix< T > & , const DenseMatrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::multElements (const DenseMatrix< T > & , const Matrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::multElements (const DenseMatrix< T > & , const DenseMatrix< T > &) [inline]
template<typename T> Elem_ref< T > Matrix< T >::operator() (size_type m, size_type n) [inline]
Overloaded operator for extracting elements from the Matrix object.
Parameters
m Row position of element.
n Column position of element.
References LMX_THROW.
template<typename T> Matrix<T> Matrix< T >::operator* (const Matrix< T > & B) const [inline]
Overloaded operator for multiplying two Matrix objects.
References Matrix< T >::cols(), and Matrix< T >::mult().
template<typename T> Matrix<T> Matrix< T >::operator* (const DenseMatrix< T > & B) const [inline]
Overloaded operator for multiplying Matrix and DenseMatrix objects.
References Matrix< T >::writeElement().
template<typename T> Matrix<T> Matrix< T >::operator* (const T & scalar) const [inline]
Overload operator for scaling a matrix.
template<typename T> Matrix< T > & Matrix< T >::operator*= (T scalar) [inline]
Scalar multiplication operator.
Parameters
scalar Factor of scaling.
Returns
Reference to scaled matrix.
template<typename T> Matrix Matrix< T >::operator+ (const Matrix< T > & B) const [inline]
Overloaded operator for adding elements between two Matrix objects.
template<typename T> Matrix Matrix< T >::operator+ (const DenseMatrix< T > & B) const [inline]
Overloaded operator for adding elements between a Matrix and a DenseMatrix object.
template<typename T> Matrix& Matrix< T >::operator+= (const Matrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::operator+= (const DenseMatrix< T > &) [inline]
template<typename T> Matrix<T> Matrix< T >::operator- (const Matrix< T > & B) const [inline]
Overloaded operator for substracting elements between two Matrix objects.
template<typename T> Matrix Matrix< T >::operator- (const DenseMatrix< T > & B) const [inline]
Overloaded operator for substracting elements between a Matrix and a DenseMatrix object.
template<typename T> Matrix& Matrix< T >::operator-= (const Matrix< T > &) [inline]
template<typename T> Matrix& Matrix< T >::operator-= (const DenseMatrix< T > &) [inline]
template<typename T> Matrix< T > & Matrix< T >::operator/= (T scalar) [inline]
Scalar term-by-term division operator.
Parameters
scalar Factor of division.
Returns
Reference to scaled matrix.
template<typename T> Matrix& Matrix< T >::operator= (const Matrix< T > &) [inline]
template<typename T> template<typename C > Matrix<T>& Matrix< T >::operator= (const Matrix< C > &) [inline]
template<typename T> Matrix& Matrix< T >::operator= (const DenseMatrix< T > &) [inline]
template<typename T> template<typename T > Matrix<T>& Matrix< T >::operator= (const Matrix< T > & A) [inline]
Overloaded operator for equaling every element between two Matrix objects of the same type.
Parameters
A Matrix to be equal to.
References Matrix< T >::mrows, Matrix< T >::ncolumns, and Matrix< T >::type_matrix.
template<typename T> template<typename C > Matrix<T>& Matrix< T >::operator= (const Matrix< C > & A) [inline]
Overloaded operator for equaling every element between two Matrix objects of different types.
Parameters
A Matrix to be equal to.
References Matrix< T >::cols(), Matrix< T >::readElement(), and Matrix< T >::rows().
template<typename T> template<typename T > Matrix<T>& Matrix< T >::operator= (const DenseMatrix< T > & A) [inline]
Overloaded operator for equaling every element between a Matrix and a DenseMatrix object of the same type.
Parameters
A DenseMatrix to be equal to.
References getMatrixType(), and Matrix< T >::mrows.
template<typename T> const T& Matrix< T >::readElement (size_type m, size_type n) const [inline]
Function that returns the value in specified position of Matrix object.
Referenced by Matrix< T >::operator=().
template<typename T> void Matrix< T >::reset () [inline]
Reset contents to 0
template<typename T> void Matrix< T >::resize (size_type i, size_type j) [inline]
Resize the Matrix with given size parameters.
Parameters
i Rows.
j Columns.
template<typename T> void Matrix< T >::resize (const Matrix< T > & mat) [inline]
Resize the Matrix to the size of another Matrix.
Parameters
mat Constant reference to a Matrix.
References Matrix< T >::cols(), and Matrix< T >::rows().
template<typename T> size_type Matrix< T >::rows () const [inline]
Read number of rows.
Returns
Number of rows of matrix.
Referenced by Matrix< T >::operator=(), and Matrix< T >::resize().
template<typename T> void Matrix< T >::sparsePattern (Vector< size_type > & , Vector< size_type > &)
template<typename T> void Matrix< T >::sparsePattern (std::vector< size_type > & , std::vector< size_type > &)
template<typename T> void Matrix< T >::sparsePattern (DenseMatrix< T > &)
template<typename T> Matrix& Matrix< T >::subs (const Matrix< T > & A, const Matrix< T > & B) [inline]
template<typename T> Matrix& Matrix< T >::subs (const Matrix< T > & A, const DenseMatrix< T > & B) [inline]
template<typename T> Matrix& Matrix< T >::subs (const DenseMatrix< T > & A, const Matrix< T > & B) [inline]
template<typename T> void Matrix< T >::subsSolve (Vector< T > & rhs) [inline]
DOCUMENT
template<typename T> Matrix& Matrix< T >::transpose () [inline]
Function to transpose a matrix.
template<typename T> void Matrix< T >::writeElement (T theValue, size_type m, size_type n) const [inline]
Function writes the value in specified position of Matrix object.
Referenced by Matrix< T >::operator*().
Friends And Related Function Documentation
template<typename T> friend class DenseMatrix< T > [friend]
template<typename T> friend class LinearSystem< T > [friend]
template<typename T> template<typename C > void lmx::latexPrint (std::ofstream & os, char * mat_name, Matrix< C > & mat, int prec) [friend]
Function to typeset a matrix to a file stream.
Parameters
os File stream to write to.
mat_name Name that will be given to matrix in typesetting. It's not the matrix variable name.
mat The Matrix variable to be typeset.
prec Precision of numbers (number of digits to be used in output).
template<typename T> friend class LMXTester [friend]
template<typename T> Matrix transposed (const Matrix< T > & mat_in) [friend]
Function to get a transposed copy of a matrix.
Parameters
mat_in Matrix to be transposed.
Returns
A new Matrix object with mat_in transposed.
template<typename T> friend class Vector< T > [friend]
Member Data Documentation
template<typename T> size_type Matrix< T >::mrows [protected]
Number of rows in matrix object.
Referenced by Matrix< T >::operator=().
template<typename T> size_type Matrix< T >::ncolumns [protected]
Number of colums in matrix object.
Referenced by Matrix< T >::operator=().
template<typename T> Elem_ref<T>* Matrix< T >::reference [protected]
Reference pointer to an element in type_matrix.
template<typename T> Data_mat<T>* Matrix< T >::type_matrix [protected]
Pointer to the container type.
Referenced by Matrix< T >::operator=().
The documentation for this class was generated from the following file:
src/LMX/lmx_mat_matrix.h