lmx::Type_gmmVector_sparse< T > Class Template Reference
Template class Type_gmmVector_sparse.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_type_gmmvector_sparse1.h>
Public Member Functions
Type_gmmVector_sparse ()
Empty constructor.
Type_gmmVector_sparse (size_type, size_type)
Type_gmmVector_sparse (char *input_file)
~Type_gmmVector_sparse ()
Destructor.
void resize (size_type, size_type)
const T & readElement (const size_type &mrows, const size_type &ncolumns) const
void writeElement (T value, const size_type &mrows, const size_type &ncolumns)
void addElement (T value, const size_type &mrows, const size_type &ncolumns)
size_type getRows () const
size_type getCols () const
void equals (const Data< T > *vector_in)
void add (const Data< T > *vector_in_1)
void substract (const Data< T > *vector_in_1)
void multiplyScalar (const T &scalar)
void multiplyElements (const Data< T > *vector_in)
void cleanBelow (const double factor)
void readDataFile (const char *input_file)
void writeDataFile (const char *output_file)
void clear ()
void reset ()
gmm::wsvector< T > * data_pointer ()
Detailed Description
template<typename T>class lmx::Type_gmmVector_sparse< T >
Template class Type_gmmVector_sparse.
This class implements the methods defined in virtual class data_mat so the Vector type `std::vector` can be used in lmx. For details about the caracteristics of this matrix type, see the STL library manual and code.
Parameters
contents Corresponds to a std::vector and it's the base of the methods implemented for this class.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T > lmx::Type_gmmVector_sparse< T >::Type_gmmVector_sparse () [inline]
Empty constructor.
template<typename T > lmx::Type_gmmVector_sparse< T >::Type_gmmVector_sparse (size_type rows, size_type columns)
Standard constructor. Creates a new object with parameter contents resized to (columns) dimension.
Parameters
rows New size of dense stdVector.
columns Not used.
template<typename T > lmx::Type_gmmVector_sparse< T >::Type_gmmVector_sparse (char * input_file)
Constructor from a data file. Creates a new object reading data from a file.
Parameters
input_file Name of file to read from.
template<typename T > lmx::Type_gmmVector_sparse< T >::~Type_gmmVector_sparse () [inline]
Destructor.
Member Function Documentation
template<typename T > void lmx::Type_gmmVector_sparse< T >::add (const Data< T > * vector_in_1) [inline], [virtual]
Add method. Adds the the input vector parameter's elements to the object's contents. Necessary for overloading the `+=` operator.
Parameters
vector_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::addElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Add element method. Implements a method for adding data on the Harwell-Boeing matrix. Copy-pasted from writeElement.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
value Numerical type value.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::cleanBelow (const double factor) [inline], [virtual]
Traspose method. Swaps elements with respect to the diagonal: A(i,j) = A(j,i) Clean below method. Makes equal to zero every element below given factor.
Parameters
factor Reference value for cleaning.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::clear () [inline], [virtual]
Clear method. Wipes all data. < Vector data contents.
Implements lmx::Data< T >.
template<typename T > gmm::wsvector<T>* lmx::Type_gmmVector_sparse< T >::data_pointer () [inline]
Data pointer method Gives the direction in memory of (pointer to) the object.
Returns
A pointer to the vector's contents (Type_gmmVector_sparse).
Referenced by lmx::LinearSystem< T >::solveYourself().
template<typename T > void lmx::Type_gmmVector_sparse< T >::equals (const Data< T > * vector_in) [inline], [virtual]
Copy method. Equals the data in the object's contents to those given by the input vector's parameter.
Parameters
vector_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > size_type lmx::Type_gmmVector_sparse< T >::getCols () const [inline], [virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implements lmx::Data< T >.
template<typename T > size_type lmx::Type_gmmVector_sparse< T >::getRows () const [inline], [virtual]
Method for knowing the number of data rows.
Returns
Number of rows.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::multiplyElements (const Data< T > * vector_in) [inline], [virtual]
Method multiplying element-by-element of two arrays. One would be the object's contents and the other the parameter's contents. Necessary for implementing Vector to Vector multElements.
Parameters
vector_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T > void lmx::Type_gmmVector_sparse< T >::multiplyScalar (const T & scalar) [inline], [virtual]
Multiply scalar method. Multiplies the object's vector (contents) with a scalar. Necessary for overloading the `*` operator.
Parameters
scalar A scalar factor of template's class.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::readDataFile (const char * input_file) [inline], [virtual]
Read data method. Opens the file specified and reads the vector's data in it.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_vec< T >.
References lmx::Type_gmmVector_sparse< T >::resize().
template<typename T > const T& lmx::Type_gmmVector_sparse< T >::readElement (const size_type & mrows, const size_type & ncolumns) const [inline], [virtual]
Read element method. Implements a method for reading data of the sparse matrix.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
Returns
Value of the element in the position given by the parameters.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::reset () [inline], [virtual]
Reset method.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::resize (size_type mrows, size_type ncolumns) [virtual]
Resize method. Changes the size of the contents parameter.
Parameters
mrows New value for size of Vector.
ncolumns Not used.
Implements lmx::Data< T >.
Referenced by lmx::Type_gmmVector_sparse< T >::readDataFile().
template<typename T > void lmx::Type_gmmVector_sparse< T >::substract (const Data< T > * vector_in_1) [inline], [virtual]
Substract method. Substracts the the input vector parameter's elements to the object's contents. Necessary for overloading the `-=` operator.
Parameters
vector_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::writeDataFile (const char * output_file) [inline], [virtual]
Write data method. Opens the file specified and writes the vector's data in it.
Parameters
output_file Name of the file to be read.
Implements lmx::Data_vec< T >.
template<typename T > void lmx::Type_gmmVector_sparse< T >::writeElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Write element method. Implements a method for writing data on the sparse matrix.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
value Numerical type value.
Implements lmx::Data< T >.
The documentation for this class was generated from the following file:
src/LMX/lmx_mat_type_gmmvector_sparse1.h