lmx::LU< T > Class Template Reference
Template class LU for solving linear systems.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_linsolvers_lu.h>
Public Member Functions
LU ()
LU (Matrix< T > *, Vector< T > *)
LU (Matrix< T > *, Matrix< T > *)
~LU ()
void lu ()
void forSub (Vector< T > &)
void backSub (Vector< T > &)
Vector< T > & solve ()
Matrix< T > & solve_nrhs ()
Detailed Description
template<typename T>class lmx::LU< T >
Template class LU for solving linear systems.
Author
Juan Carlos García Orden.
Constructor & Destructor Documentation
template<typename T> lmx::LU< T >::LU () [inline]
Empty constructor.
template<typename T > lmx::LU< T >::LU (Matrix< T > * mat_in, Vector< T > * vec_in)
Standard constructor.
Parameters
mat_in Pointer to Matrix.
vec_in Pointer to Vector.
References LMX_THROW, and lmx::Vector< T >::resize().
template<typename T > lmx::LU< T >::LU (Matrix< T > * mat_in, Matrix< T > * mat_rhs_in)
Standard constructor for nrhs Matrix.
Parameters
mat_in Pointer to Matrix.
mat_rhs_in Pointer to Matrix.
References LMX_THROW, and lmx::Vector< T >::resize().
template<typename T> lmx::LU< T >::~LU () [inline]
Destructor
Member Function Documentation
template<typename T > void lmx::LU< T >::backSub (Vector< T > & c)
Backward substitution Given an upper triangular, nonsingular dim by dim matrix mat and an dim-vector c, obtains vector y which solves mat*y=c vector y replaces c
References lmx::Vector< T >::readElement().
template<typename T > void lmx::LU< T >::forSub (Vector< T > & c)
Forward substitution Given a unit lower triangular, nonsingular dim by dim matrix mat, and dim-vector c obtains vector y which solves mat*y = c vector y replaces c
References lmx::Vector< T >::readElement().
template<typename T > void lmx::LU< T >::lu ()
Perform LU-decomposition Upon return the coefficients of L and U replace those of the input dim-by-dim nonsingular matrix mat.
References LMX_THROW, lmx::Vector< T >::readElement(), and lmx::Vector< T >::resize().
template<typename T > Vector< T > & lmx::LU< T >::solve ()
Solve system
Returns
Reference to solution vector.
Referenced by lmx::LinearSystem< T >::solveYourself().
template<typename T > Matrix< T > & lmx::LU< T >::solve_nrhs ()
Solve n-rhs system
Returns
Reference to solution vector.
Referenced by lmx::LinearSystem< T >::solveYourselfMatrix().
The documentation for this class was generated from the following file:
src/LMX/lmx_linsolvers_lu.h