Cone Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/cone.h>
Public Member Functions
Cone ()
Cone (std::string, double, double, double, int)
~Cone ()
void setSections (double)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
Protected Attributes
double slope
double initDiam
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Cone::Cone ()
Cone::Cone (std::string type_in, double z0_in, double length_in, double initDiam_in, int sectors_in)
References Geometry::gridWidth, initDiam, Geometry::length, and slope.
Cone::~Cone ()
Member Function Documentation
void Cone::computeGeometry () [virtual]
Implements Geometry.
Reimplemented in Cone2.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, initDiam, Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, slope, and Geometry::z0.
void Cone::computeIntersection (Particle * particle) [virtual]
Implements Geometry.
Reimplemented in Cone2, and Cone2.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, and residue().
void Cone::computeNodalPower (Particle * particle) [virtual]
Implements Geometry.
Reimplemented in Cone2.
References Particle::getEnergy(), Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Geometry::length, Geometry::nodes, Geometry::paramTrajectories, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cone::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
References Geometry::length, slope, and Geometry::z0.
Referenced by computeIntersection().
void Cone::outputPowerDensityFile () [virtual]
Implements Geometry.
Reimplemented in Cone2.
References Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cone::outputPowerFile (int particles) [virtual]
Implements Geometry.
Reimplemented in Cone2.
References Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void Cone::outputTable () [virtual]
Implements Geometry.
Reimplemented in Cone2.
void Cone::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
References Geometry::length, slope, and Geometry::z0.
Referenced by computeIntersection().
void Cone::setSections (double distance) [virtual]
Implements Geometry.
Reimplemented in Cone2.
References Geometry::length, and Geometry::sections.
Member Data Documentation
double Cone::initDiam [protected]
Referenced by computeGeometry(), and Cone().
double Cone::slope [protected]
Referenced by computeGeometry(), Cone(), jacobian(), and residue().
The documentation for this class was generated from the following files:
src/cone.h
src/cone.cpp