Cone2 Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/cone2-bak.h>
Public Member Functions
Cone2 ()
Cone2 (std::string, double, double, double, double, int)
~Cone2 ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
Cone2 ()
Cone2 (std::string, double, double, double, double, int)
~Cone2 ()
void setSections (double)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
Protected Attributes
double slope
double initDiam
double apparentLength
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Cone2::Cone2 ()
Cone2::Cone2 (std::string type_in, double z0_in, double length_in, double initDiam_in, double finalDiam_in, int par3_in)
References Geometry::gridWidth, initDiam, Geometry::length, and slope.
Cone2::~Cone2 ()
Cone2::Cone2 ()
Cone2::Cone2 (std::string , double , double , double , double , int)
Cone2::~Cone2 ()
Member Function Documentation
void Cone2::computeGeometry () [virtual]
Reimplemented from Cone.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, initDiam, Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, slope, and Geometry::z0.
void Cone2::computeIntersection (Particle * particle) [virtual]
Reimplemented from Cone.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, and residue().
void Cone2::computeIntersection (Particle *) [virtual]
Reimplemented from Cone.
void Cone2::computeNodalPower (Particle * particle) [virtual]
Reimplemented from Cone.
References Particle::getEnergy(), Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Geometry::length, Geometry::nodes, Geometry::paramTrajectories, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cone2::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
References Geometry::length, slope, and Geometry::z0.
Referenced by computeIntersection().
void Cone2::jacobian (lmx::Matrix< double > & , lmx::Vector< double > &)
void Cone2::outputPowerDensityFile () [virtual]
Reimplemented from Cone.
References Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cone2::outputPowerFile (int particles) [virtual]
Reimplemented from Cone.
References Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void Cone2::outputTable () [virtual]
Reimplemented from Cone.
void Cone2::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
References Geometry::length, slope, and Geometry::z0.
Referenced by computeIntersection().
void Cone2::residue (lmx::Vector< double > & , lmx::Vector< double > &)
void Cone2::setSections (double distance) [virtual]
Reimplemented from Cone.
References Geometry::length, and Geometry::sections.
Member Data Documentation
double Cone2::apparentLength [protected]
double Cone2::initDiam [protected]
Referenced by computeGeometry(), and Cone2().
double Cone2::slope [protected]
Referenced by computeGeometry(), Cone2(), jacobian(), and residue().
The documentation for this class was generated from the following files:
src/cone2-bak.h
src/cone2.h
src/cone2-bak.cpp
src/cone2.cpp