Ring Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/ring.h>
Public Member Functions
Ring ()
Ring (std::string, double, double, double, int)
~Ring ()
void setSections (double)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
Additional Inherited Members
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Ring::Ring ()
Ring::Ring (std::string type_in, double par0_in, double par1_in, double par2_in, int par3_in)
References Geometry::gridWidth.
Ring::~Ring ()
Member Function Documentation
void Ring::computeGeometry () [virtual]
Implements Geometry.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ring::computeIntersection (Particle * particle) [virtual]
Implements Geometry.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, and residue().
void Ring::computeNodalPower (Particle * particle) [virtual]
Implements Geometry.
References Particle::getEnergy(), Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Geometry::length, Geometry::nodes, Geometry::paramTrajectories, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ring::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
Referenced by computeIntersection().
void Ring::outputPowerDensityFile () [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Ring::outputPowerFile (int particles) [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void Ring::outputTable () [virtual]
Implements Geometry.
void Ring::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
Referenced by computeIntersection().
void Ring::setSections (double distance) [virtual]
Implements Geometry.
References Geometry::sections.
The documentation for this class was generated from the following files:
src/ring.h
src/ring.cpp