lmx::NLSolver< Sys, T > Class Template Reference
Template class NLSolver. Non-linear systems implementation: `R(q) = 0` .
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_nlsolvers.h>
Public Member Functions
NLSolver ()
~NLSolver ()
void setInfo (int level)
template<class C >
void setInitialConfiguration (const lmx::Vector< C > &q_in)
void setSystem (Sys &system_in)
void setDeltaInResidue (bool state=1)
void setResidue (void(Sys::*residue_in)(lmx::Vector< T > &, lmx::Vector< T > &))
void setJacobian (void(Sys::*jacobian_in)(lmx::Matrix< T > &, lmx::Vector< T > &))
void setConvergence (double eps_in)
void setConvergence (bool(Sys::*convergence_in)(lmx::Vector< T > &))
void setConvergence (bool(Sys::*convergence_in)(lmx::Vector< T > &, lmx::Vector< T > &))
void setConvergence (bool(Sys::*convergence_in)(lmx::Vector< T > &, lmx::Vector< T > &, lmx::Vector< T > &))
bool convergence ()
void solve (int max_iter=100)
lmx::Vector< T > & getSolution ()
void setSparse (std::vector< size_type > &rows, std::vector< size_type > columns)
Detailed Description
template<typename Sys, typename T = double>class lmx::NLSolver< Sys, T >
Template class NLSolver. Non-linear systems implementation: `R(q) = 0` .
This class permits the creation of a non-linear solver object.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename Sys, typename T = double> lmx::NLSolver< Sys, T >::NLSolver () [inline]
Empty constructor.
template<typename Sys, typename T = double> lmx::NLSolver< Sys, T >::~NLSolver () [inline]
Destructor.
Member Function Documentation
template<typename Sys , class T > bool lmx::NLSolver< Sys, T >::convergence ()
Internal convergence criteria. Is used if no external convergence function is set.
template<typename Sys, typename T = double> lmx::Vector<T>& lmx::NLSolver< Sys, T >::getSolution () [inline]
Solution vector read-write access.
Returns
Reference to the solution vector.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setConvergence (double eps_in) [inline]
Defines the epsilon value for the L2 norm.
Parameters
eps_in Value of the maximum L2 limit.
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setConvergence (bool(Sys::*)(lmx::Vector< T > &) convergence_in) [inline]
Defines the optional member function for convergence evaluation with residue parameter.
Parameters
convergence_in Convergence evaluation member function.
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setConvergence (bool(Sys::*)(lmx::Vector< T > &, lmx::Vector< T > &) convergence_in) [inline]
Defines the optional member function for convergence evaluation with residue and configuration parameters.
Parameters
convergence_in Convergence evaluation member function.
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setConvergence (bool(Sys::*)(lmx::Vector< T > &, lmx::Vector< T > &, lmx::Vector< T > &) convergence_in) [inline]
Defines the optional member function for convergence evaluation with residue, configuration and increment vector parameters.
Parameters
convergence_in Convergence evaluation member function.
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setDeltaInResidue (bool state = 1) [inline]
Sets whether the parameter in Residue function corresponds to the actual variables configuration or indicates the increment of those variables.
Parameters
state TRUE (default) if the variable's increment is going to be passed.
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setInfo (int level) [inline]
Set information level.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys, typename T = double> template<class C > void lmx::NLSolver< Sys, T >::setInitialConfiguration (const lmx::Vector< C > & q_in) [inline]
Takes a lmx::Vector for initial value guess and dimensioning the problem.
Parameters
q_in Initial guess values.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setJacobian (void(Sys::*)(lmx::Matrix< T > &, lmx::Vector< T > &) jacobian_in) [inline]
Defines the member function that computes the tangent to the residue.
Parameters
jacobian_in Jacobian member function.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setResidue (void(Sys::*)(lmx::Vector< T > &, lmx::Vector< T > &) residue_in) [inline]
Defines the member function that computes the residue.
Parameters
residue_in Residue member function.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setSparse (std::vector< size_type > & rows, std::vector< size_type > columns) [inline]
template<typename Sys, typename T = double> void lmx::NLSolver< Sys, T >::setSystem (Sys & system_in) [inline]
Sets witch Sys object is going to be used for member function calls.
Parameters
system_in The Sys object.
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
template<typename Sys , class T > void lmx::NLSolver< Sys, T >::solve (int max_iter = 100)
Solve function. Initiates the nl-solver loop.
Parameters
max_iter Defines the maximun number of iterations for each iteration.
References LMX_THROW, lmx::nl_solver_type, and lmx::LinearSystem< T >::solveYourself().
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
The documentation for this class was generated from the following file:
src/LMX/lmx_nlsolvers.h