lmx::Vector< T > Class Template Reference
Template class Vector.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_data_mat.h>
Public Member Functions
Vector ()
Vector (size_type)
Vector (const Vector &)
~Vector ()
size_type size () const
void load (char *)
void save (char *)
void fillIdentity (T factor=static_cast< T >(1))
void fillRandom (T factor=static_cast< T >(1))
Elem_ref< T > & operator() (size_type)
Vector & operator= (const Matrix< T > &)
Vector & operator= (const Vector< T > &)
template<typename C >
Vector< T > & operator= (const Vector< C > &)
Vector & operator+= (const Vector &)
Vector & operator-= (const Vector &)
Vector & operator*= (const T &)
Vector & add (const Vector< T > &, const Vector< T > &)
Vector & subs (const Vector< T > &, const Vector< T > &)
Vector & mult (const Matrix< T > &, const Vector< T > &)
Vector & mult (const DenseMatrix< T > &, const Vector< T > &)
Vector & mult (const T &)
Vector & mult (const Vector< T > &, const T &)
Vector & mult (const T &, const Vector< T > &)
Vector & mult (const Vector< T > &, const Vector< T > &)
Vector & multElements (const Vector< T > &)
Vector & multElements (const Vector< T > &, const Vector< T > &)
T norm1 () const
T norm2 () const
T readElement (size_type m) const
void writeElement (T theValue, size_type m) const
void addElement (T theValue, size_type m) const
void clean (double factor)
void clear ()
void reset ()
void resize (size_type i)
void resize (const Vector &vec)
Vector operator+ (const Vector< T > &B) const
Vector operator- (const Vector< T > &B) const
T operator* (const Vector &B) const
Vector operator* (const T &a) const
Friends
class LinearSystem< T >
void latexPrint (std::ofstream &os, char *vec_name, Vector &vec, int prec)
Detailed Description
template<typename T>class lmx::Vector< T >
Template class Vector.
This class permits the creation of vector objects. The Vector class, which derives from Matrix class, has one parameter (nrows) that stores the dimension of the vector's container. The data is stored in an atribute (*type_vector) that points to some class which derives from the Data_vec class.
Parameters
elements The size of the Data Container (Data_vec).
reference An Elem_ref object for r/w data access.
*type_matrix The pointer to the vector data container.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename T > Vector< T >::Vector ()
Empty constructor.
References lmx::getVectorType(), and LMX_THROW.
template<typename T > Vector< T >::Vector (size_type rows) [explicit]
Standard constructor.
Parameters
rows Number of Vector's rows.
References lmx::getVectorType(), and LMX_THROW.
template<typename T > Vector< T >::Vector (const Vector< T > & A)
Copy constructor.
Parameters
A Vector to copy from.
References lmx::getVectorType(), and LMX_THROW.
template<typename T > Vector< T >::~Vector ()
Destructor.
Member Function Documentation
template<typename T> Vector< T > & Vector< T >::add (const Vector< T > & A, const Vector< T > & B) [inline]
(Cancelled function) Operator for multiplying Vector and Matrix objects.
Performs typical vector operation: b * A = c, where b & c are vectors and A is a Matrix.
Parameters
A Matrix reference for second LHS term.
b Vector reference for first LHS term.
Returns
A new Vector (c = b^T * A). (Cancelled function) Operator for multiplying Vector and DenseMatrix objects.
Performs typical vector operation: b * A = c, where b & c are vectors and A is a DenseMatrix.
Parameters
A DenseMatrix reference for second LHS term.
b Vector reference for first LHS term.
Returns
A new Vector (c = b^T * A). Element adding function.
Adds two Vectors' elements and saves result in object.
Parameters
A A vector.
B A vector.
Returns
Reference to result.
References LMX_THROW, and lmx::Vector< T >::size().
Referenced by lmx::Cg< T >::solve().
template<typename T> void lmx::Vector< T >::addElement (T theValue, size_type m) const [inline]
Function writes the value in specified position of Vector object.
template<typename T> void lmx::Vector< T >::clean (double factor) [inline]
Cleans all numbers below given factor.
template<typename T> void lmx::Vector< T >::clear () [inline]
Clears the object's contents.
template<typename T> void Vector< T >::fillIdentity (T factor = static_cast<T>(1))
Cleans vector and sets all terms to specified value.
Parameters
factor Value of terms. Default is unit value.
template<typename T> void Vector< T >::fillRandom (T factor = static_cast<T>(1))
Function for filling a vector with random numbers
Parameters
factor Scales the random numbers (default value is unity).
template<typename T > void Vector< T >::load (char * input_file)
Method for reading a Vector from a file.
Parameters
input_file Name of the file to read.
template<typename T> Vector< T > & Vector< T >::mult (const Matrix< T > & A, const Vector< T > & b) [inline]
Function for multiplying Matrix and Vector objects. Performs typical vector operation: A * b = c, where b & c are vectors and A is a Matrix.
c would be the object witch its invoked from.
This function is specialized for some Matrix and Vector types.
Parameters
A Matrix reference for first LHS term.
b Const Vector reference for second LHS term.
References lmx::getMatrixType(), lmx::getVectorType(), LMX_THROW, lmx::Vector< T >::readElement(), and lmx::Vector< T >::size().
Referenced by lmx::Vector< int >::operator*(), lmx::operator*(), and lmx::Cg< T >::solve().
template<typename T> Vector< T > & Vector< T >::mult (const DenseMatrix< T > & A, const Vector< T > & b) [inline]
Function for multiplying DenseMatrix and Vector objects. Performs typical vector operation: A * b = c, where b & c are vectors and A is a DenseMatrix.
c would be the object witch its invoked from.
This function is specialized for some Matrix and Vector types.
Parameters
A DenseMatrix reference for first LHS term.
b Const Vector reference for second LHS term.
References LMX_THROW, lmx::DenseMatrix< T >::readElement(), lmx::Vector< T >::readElement(), and lmx::Vector< T >::size().
template<typename T> Vector< T > & Vector< T >::mult (const T & scalar) [inline]
Scaling function.
Scales each element in Vector with specified scalar factor.
Parameters
scalar Scaling factor.
Returns
Reference to result.
template<typename T> Vector< T > & Vector< T >::mult (const Vector< T > & B, const T & scalar) [inline]
Scaling function. (scalar in RHS)
Scales each element in Vector B with specified scalar factor and saves the result in object.
Parameters
B Vector to scale.
scalar Scaling factor.
Returns
Reference to result.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T> Vector< T > & Vector< T >::mult (const T & scalar, const Vector< T > & B) [inline]
Scaling function (scalar in LHS)
Scales each element in Vector B with specified scalar factor and saves the result in object.
Parameters
scalar Scaling factor.
B Vector to scale.
Returns
Reference to result.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T> Vector< T > & Vector< T >::mult (const Vector< T > & A, const Vector< T > & B) [inline]
Cross product
Computes the cross product A x B. Not optimized but useful
Parameters
A Vector of size m.
B Vector of size m.
Returns
Reference to result.
References LMX_THROW, lmx::Vector< T >::readElement(), and lmx::Vector< T >::size().
template<typename T> Vector< T > & Vector< T >::multElements (const Vector< T > & B) [inline]
Internal product
Element-to-element multiplication between Vector objects.
Parameters
B Vector to multiply to.
Returns
Reference to result.
Referenced by lmx::Cg< T >::solve().
template<typename T> Vector< T > & Vector< T >::multElements (const Vector< T > & A, const Vector< T > & B) [inline]
Internal product of to Vectors
Element-to-element multiplication between Vector objects.
Parameters
A A Vector.
B A Vector.
Returns
Reference to result.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T > T Vector< T >::norm1 () const [inline]
Computes the first norm of the Vector.
Returns
The first norm of object.
References cofe::norm().
template<typename T > T Vector< T >::norm2 () const [inline]
Computes de second (euclidean) norm of the Vector.
Returns
The second (euclidean) norm of object.
References cofe::norm().
template<typename T > Elem_ref< T > & Vector< T >::operator() (size_type row) [inline]
Overload of element extraction method.
Parameters
row Position in Vector for the element to extract.
Returns
element referenced.
References LMX_THROW.
template<typename T> T lmx::Vector< T >::operator* (const Vector< T > & B) const [inline]
Operator for scalar product of two Vector objects. Performs typical vector operation: A * B = c, where A & B are vectors and c is a scalar.
Parameters
B Vector reference for second LHS term.
Returns
The numeric result of the operation (type: double).
template<typename T> Vector lmx::Vector< T >::operator* (const T & a) const [inline]
Overload operator for multiplying a scalar and a Vector object.
Parameters
a scalar reference.
Returns
A new Vector (mult = (*this) * a).
template<typename T> Vector< T > & Vector< T >::operator*= (const T & scalar) [inline]
Scaling operator.
Scales each element in Vector with specified scalar factor.
Parameters
scalar Scaling factor.
Returns
Reference to result.
template<typename T> Vector lmx::Vector< T >::operator+ (const Vector< T > & B) const [inline]
Operator for adding two Vector objects. Performs typicar vector operation: A + B = C, where A, B & C are vectors. A is Vector *this.
Parameters
B Vector reference for second LHS term.
Returns
The numeric result of the operation: C = A + B.
template<typename T > Vector< T > & Vector< T >::operator+= (const Vector< T > & b) [inline]
Overloaded operator for assigning the addition of elements between two Vector objects.
Parameters
b Vector to equal to.
Returns
A reference to the Vector object.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T> Vector lmx::Vector< T >::operator- (const Vector< T > & B) const [inline]
Operator for substracting two Vector objects. Performs typicar vector operation: A - B = C, where A, B & C are vectors. A is Vector *this.
Parameters
B Vector reference for second LHS term.
Returns
The numeric result of the operation: C = A - B.
template<typename T > Vector< T > & Vector< T >::operator-= (const Vector< T > & b) [inline]
Overloaded operator for assigning the substraction of elements between two Vector objects.
Parameters
b Vector to equal to.
Returns
A reference to the Vector object.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T> Vector< T > & Vector< T >::operator= (const Matrix< T > & A) [inline]
Overload of equals operator. Equals every element between the Vector and the first column of a Matrix object.
Parameters
A Matrix to equal to.
Returns
A reference to the Vector object.
template<typename T> Vector< T > & Vector< T >::operator= (const Vector< T > & v) [inline]
Overload of equals operator. Equals every element between two Vector objects of the same type.
Parameters
v Vector to equal to.
Returns
A reference to the Vector object.
References LMX_THROW, and lmx::Vector< T >::size().
template<typename T > template<typename C > Vector< T > & Vector< T >::operator= (const Vector< C > & v) [inline]
Overload of equals operator. Equals every element between two Vector objects of different types.
Parameters
v Vector to equal to.
Returns
A reference to the Vector object.
References LMX_THROW, lmx::Vector< T >::readElement(), and lmx::Vector< T >::size().
template<typename T> T lmx::Vector< T >::readElement (size_type m) const [inline]
Function for reading a Vector object's element from it's known position.
Parameters
m vec's position (row) for lookup.
Returns
The element.
Referenced by lmx::LU< T >::backSub(), Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), lmx::LU< T >::forSub(), lmx::Gesv< T >::Gesv(), Cone2::jacobian(), Ring::jacobian(), Ogive::jacobian(), Cylinder::jacobian(), Cone::jacobian(), TwoPlates::jacobian(), lmx::LU< T >::lu(), lmx::Vector< T >::mult(), lmx::Vector< int >::operator*(), lmx::Vector< T >::operator=(), Cone2::residue(), Ring::residue(), Ogive::residue(), Cylinder::residue(), Cone::residue(), TwoPlates::residue(), and lmx::Superlu< T >::setVectors().
template<typename T> void lmx::Vector< T >::reset () [inline]
Reset the object's contents.
template<typename T> void lmx::Vector< T >::resize (size_type i) [inline]
Resize the Vector with given size parameter.
Parameters
i New size.
Referenced by lmx::LU< T >::LU(), and lmx::LU< T >::lu().
template<typename T> void lmx::Vector< T >::resize (const Vector< T > & vec) [inline]
Resize the Vector to the size of another Vector.
Parameters
vec Constant reference to a Vector.
template<typename T > void Vector< T >::save (char * output_file)
Method for writing a Vector to a file.
Parameters
output_file Name of the file to write.
template<typename T> size_type lmx::Vector< T >::size () const [inline]
Read number of rows.
Returns
Dimension of vector.
Referenced by lmx::Vector< T >::add(), lmx::LinearSystem< double >::LinearSystem(), lmx::Vector< T >::mult(), lmx::Vector< T >::multElements(), lmx::Vector< int >::operator*(), lmx::operator*(), lmx::Vector< int >::operator+(), lmx::Vector< T >::operator+=(), lmx::Vector< int >::operator-(), lmx::Vector< T >::operator-=(), lmx::operator<<(), lmx::Vector< T >::operator=(), lmx::Vector< int >::resize(), lmx::Configuration< T >::setInitialCondition(), lmx::NLSolver< lmx::DiffProblemSecond< Sys, T >, T >::setInitialConfiguration(), lmx::NLSolverDouble< T >::setInitialConfiguration1(), lmx::NLSolverDouble< T >::setInitialConfiguration2(), lmx::Type_csc< T >::setSparsePattern(), and lmx::Vector< T >::subs().
template<typename T> Vector< T > & Vector< T >::subs (const Vector< T > & A, const Vector< T > & B) [inline]
Element substracting function. Substract two Vectors' elements and saves result in object.
Parameters
A A vector.
B A vector.
Returns
Reference to result.
References LMX_THROW, and lmx::Vector< T >::size().
Referenced by lmx::Cg< T >::solve().
template<typename T> void lmx::Vector< T >::writeElement (T theValue, size_type m) const [inline]
Function writes the value in specified position of Vector object.
Referenced by lmx::Superlu< T >::get_solution(), Cone2::residue(), Ring::residue(), Ogive::residue(), Cylinder::residue(), Cone::residue(), and TwoPlates::residue().
Friends And Related Function Documentation
template<typename T> void latexPrint (std::ofstream & os, char * vec_name, Vector< T > & vec, int prec) [friend]
Function to typeset a vector to a file stream.
Parameters
os File stream to write to.
vec_name Name that will be given to vector in typesetting. It's not the vector variable name.
vec The Vector variable to be typeset.
prec Maximum numeric precision (max. number of digits to be used in output).
template<typename T> friend class LinearSystem< T > [friend]
The documentation for this class was generated from the following files:
src/LMX/lmx_mat_data_mat.h
src/LMX/lmx_mat_vector.h