Particle Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/particle.h>
Public Member Functions
Particle ()
Particle (double &, double &, double &, double &, double &, double &, double &)
~Particle ()
double & getX ()
double & getY ()
double & getZ ()
double & getXdiv ()
double & getYdiv ()
double & getZdiv ()
double & getEnergy ()
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Particle::Particle ()
Particle::Particle (double & x_in, double & xdiv_in, double & y_in, double & ydiv_in, double & z_in, double & zdiv_in, double & energy_in)
Particle::~Particle ()
Member Function Documentation
double& Particle::getEnergy () [inline]
Referenced by Ring::computeNodalPower(), Cylinder::computeNodalPower(), Ogive::computeNodalPower(), Cone::computeNodalPower(), and Cone2::computeNodalPower().
double& Particle::getX () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), Ring::computeNodalPower(), Cylinder::computeNodalPower(), Ogive::computeNodalPower(), Cone::computeNodalPower(), and Cone2::computeNodalPower().
double& Particle::getXdiv () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), Ring::computeNodalPower(), Cylinder::computeNodalPower(), Ogive::computeNodalPower(), Cone::computeNodalPower(), and Cone2::computeNodalPower().
double& Particle::getY () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), Ring::computeNodalPower(), Cylinder::computeNodalPower(), Ogive::computeNodalPower(), Cone::computeNodalPower(), and Cone2::computeNodalPower().
double& Particle::getYdiv () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), Ring::computeNodalPower(), Cylinder::computeNodalPower(), Ogive::computeNodalPower(), Cone::computeNodalPower(), and Cone2::computeNodalPower().
double& Particle::getZ () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), TwoPlates::computeIntersection(), and Cylinder::computeNodalPower().
double& Particle::getZdiv () [inline]
Referenced by Cone2::computeIntersection(), Ring::computeIntersection(), Cylinder::computeIntersection(), Ogive::computeIntersection(), Cone::computeIntersection(), and TwoPlates::computeIntersection().
The documentation for this class was generated from the following files:
src/particle.h
src/particle.cpp