lmx::Superlu< T > Class Template Reference
Template class LinearSystem. Linear systems implementation: `A*x = b` .
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_linsolvers_superlu_interface.h>
Public Member Functions
Superlu (size_type &, size_type &, size_type &, std::vector< size_type > &, std::vector< size_type > &, std::vector< T > &)
Superlu (size_type &, size_type &, size_type &, std::vector< size_type > &, std::vector< size_type > &, std::vector< T > &, std::vector< T > &, std::vector< T > &)
Superlu (size_type &, size_type &, size_type &, std::vector< size_type > &, std::vector< size_type > &, std::vector< T > &, T *, T *)
Superlu (size_type &, size_type &, size_type &, size_type *, size_type *, T *, T *, T *)
Superlu (size_type &, size_type &, size_type &, size_type *, size_type *, T *, std::vector< T > &, std::vector< T > &)
~Superlu ()
void init ()
void initMatrix ()
void initVectors ()
void calc (int)
void recalc (int)
void get_solution (std::vector< T > &)
void get_solution (Vector< T > &)
void setVectors (Vector< T > &b_in)
void setb (T *)
void setb (std::vector< T > &)
void setA (size_type &m_in, size_type &n_in, size_type &nnz_in, std::vector< size_type > &asub_in, std::vector< size_type > &xa_in, std::vector< T > &a_in)
void recalc1 (int)
void recalc2 (int)
void factorize (void)
void subsSolve (void)
void get_solutionB (std::vector< T > &)
Detailed Description
template<typename T>class lmx::Superlu< T >
Template class LinearSystem. Linear systems implementation: `A*x = b` .
This class permits the creation of a linear system object. Each object has three parameters, corresponding to each of the matrices or vectors base of the problem. The basic methods solve the problem and add functionality to control the solution procedure. Not only one solver can be used as well as the number data type (class) may be differ between the input and the one used to solve the system.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T > lmx::Superlu< T >::Superlu (size_type & m_in, size_type & n_in, size_type & nnz_in, std::vector< size_type > & asub_in, std::vector< size_type > & xa_in, std::vector< T > & a_in)
Constructor for STL style sparse matrix.
Parameters
m_in Number of rows of matrix.
n_in Number of columns of matrix.
nnz_in Number of non-zeros in sparse matrix.
asub_in Vector of integers.
xa_in Vector of integers.
a_in Vector of matrix's values.
template<typename T > lmx::Superlu< T >::Superlu (size_type & m_in, size_type & n_in, size_type & nnz_in, std::vector< size_type > & asub_in, std::vector< size_type > & xa_in, std::vector< T > & a_in, std::vector< T > & x_in, std::vector< T > & b_in)
Constructor for STL style sparse matrix and vectors.
Parameters
m_in Number of rows of matrix.
n_in Number of columns of matrix.
nnz_in Number of non-zeros in sparse matrix.
asub_in Vector of integers.
xa_in Vector of integers.
a_in Vector of matrix's values.
x_in Vector of solution values.
b_in Vector of RHS vector's values.
template<typename T > lmx::Superlu< T >::Superlu (size_type & m_in, size_type & n_in, size_type & nnz_in, std::vector< size_type > & asub_in, std::vector< size_type > & xa_in, std::vector< T > & a_in, T * x_in, T * b_in)
Constructor for STL style sparse matrix and c-array vectors.
Parameters
m_in Number of rows of matrix.
n_in Number of columns of matrix.
nnz_in Number of non-zeros in sparse matrix.
asub_in Vector of integers.
xa_in Vector of integers.
a_in Vector of matrix's values.
x_in Array of solution values.
b_in Array of RHS vector's values.
template<typename T > lmx::Superlu< T >::Superlu (size_type & m_in, size_type & n_in, size_type & nnz_in, size_type * asub_in, size_type * xa_in, T * a_in, T * x_in, T * b_in)
Constructor from c-array style vectors.
Parameters
m_in Number of rows of matrix.
n_in Number of columns of matrix.
nnz_in Number of non-zeros in sparse matrix.
asub_in Array of integers.
xa_in Array of integers.
a_in Array of matrix's values.
x_in Array of solution values.
b_in Array of RHS vector's values.
template<typename T > lmx::Superlu< T >::Superlu (size_type & m_in, size_type & n_in, size_type & nnz_in, size_type * asub_in, size_type * xa_in, T * a_in, std::vector< T > & x_in, std::vector< T > & b_in)
Constructor from c-array style sparse matrix and STL style vectors.
Parameters
m_in Number of rows of matrix.
n_in Number of columns of matrix.
nnz_in Number of non-zeros in sparse matrix.
asub_in Array of integers.
xa_in Array of integers.
a_in Array of matrix's values.
x_in Vector of solution values.
b_in Vector of RHS vector's values.
template<typename T > lmx::Superlu< T >::~Superlu ()
Destructor
Member Function Documentation
template<typename T > void lmx::Superlu< T >::calc (int noisy)
Function to compute solution vector.
Parameters
noisy Sets the level of output information.
template<typename T > void lmx::Superlu< T >::factorize (void)
template<typename T > void lmx::Superlu< T >::get_solution (std::vector< T > & x_out)
Writes solution in vector.
Parameters
x_out STL-style vector for writing the computed solution.
template<typename T > void lmx::Superlu< T >::get_solution (Vector< T > & x_out)
References lmx::Vector< T >::writeElement().
template<typename T > void lmx::Superlu< T >::get_solutionB (std::vector< T > & x_out)
template<typename T> void lmx::Superlu< T >::init () [inline]
References lmx::Superlu< T >::initMatrix(), and lmx::Superlu< T >::initVectors().
template<typename T > void lmx::Superlu< T >::initMatrix ()
Initialize A SuperMatrix.
Referenced by lmx::Superlu< T >::init().
template<typename T > void lmx::Superlu< T >::initVectors ()
Initialize B,X SuperMatrices.
Referenced by lmx::Superlu< T >::init().
template<typename T > void lmx::Superlu< T >::recalc (int noisy)
Function to compute solution vector using previous factorization.
Parameters
noisy Sets the level of output information.
template<typename T > void lmx::Superlu< T >::recalc1 (int noisy)
template<typename T > void lmx::Superlu< T >::recalc2 (int noisy)
template<typename T > void lmx::Superlu< T >::setA (size_type & m_in, size_type & n_in, size_type & nnz_in, std::vector< size_type > & asub_in, std::vector< size_type > & xa_in, std::vector< T > & a_in)
template<typename T > void lmx::Superlu< T >::setb (T * b_in)
template<typename T > void lmx::Superlu< T >::setb (std::vector< T > & b_in)
template<typename T > void lmx::Superlu< T >::setVectors (Vector< T > & b_in)
References lmx::Vector< T >::readElement().
template<typename T > void lmx::Superlu< T >::subsSolve (void)
The documentation for this class was generated from the following file:
src/LMX/lmx_linsolvers_superlu_interface.h