cofe::CofeUtils Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/cofe_CofeUtils.h>
Static Public Member Functions
static void error (const std::string &stri)
static void error (const std::string &stri, int code)
Member Function Documentation
static void cofe::CofeUtils::error (const std::string & stri) [inline], [static]
Referenced by cofe::TensorRank2< Dim, T >::beInverseOf(), cofe::gausselim(), inverseOf(), and cofe::jacobi().
static void cofe::CofeUtils::error (const std::string & stri, int code) [inline], [static]
The documentation for this class was generated from the following file:
src/LMX/cofe_CofeUtils.h