lmx::Type_gmm_sparse< T > Class Template Reference
Template class Type_gmm_sparse.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_type_gmm_sparse1.h>
Public Member Functions
Type_gmm_sparse ()
Empty constructor.
Type_gmm_sparse (size_type, size_type)
~Type_gmm_sparse ()
Destructor.
void resize (size_type, size_type)
void factorize ()
const T & readElement (const size_type &mrows, const size_type &ncolumns) const
void writeElement (T value, const size_type &mrows, const size_type &ncolumns)
void addElement (T value, const size_type &mrows, const size_type &ncolumns)
size_type getRows () const
size_type getCols () const
void equals (const Data< T > *matrix_in)
void add (const Data< T > *matrix_in_1)
void substract (const Data< T > *matrix_in_1)
void multiply (const Data< T > *matrix_in_1, const Data< T > *matrix_in_2)
void multiplyScalar (const T &scalar)
void multiplyElements (const Data< T > *matrix_in)
void read_mm_file (const char *input_file)
void read_hb_file (const char *input_file)
void write_hb_file (const char *input_file)
void trn ()
void cleanBelow (const double factor)
void clear ()
void reset ()
gmm::row_matrix< gmm::rsvector
*
< T > > * data_pointer ()
bool exists (size_type, size_type)
Detailed Description
template<typename T>class lmx::Type_gmm_sparse< T >
Template class Type_gmm_sparse.
This class implements the methods defined in virtual class data_mat so the matrix type `gmm::row_matrix< gmm::rsvector<T> >` can be used in lmx. For details about the caracteristics of this matrix type, see the gmm library manual and code.
Parameters
contents Corresponds to a gmm::row_matrix< gmm::rsvector<T> > and it's the base of the methods implemented for this class.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T > lmx::Type_gmm_sparse< T >::Type_gmm_sparse () [inline]
Empty constructor.
template<typename T > lmx::Type_gmm_sparse< T >::Type_gmm_sparse (size_type rows, size_type columns)
Standard constructor. Creates a new object with parameter contents resized to (rows, columns) dimension.
Parameters
rows Rows of sparse matrix.
columns Columns of sparse matrix.
template<typename T > lmx::Type_gmm_sparse< T >::~Type_gmm_sparse () [inline]
Destructor.
Member Function Documentation
template<typename T > void lmx::Type_gmm_sparse< T >::add (const Data< T > * matrix_in_1) [inline], [virtual]
Add method. Adds the the input matrix parameter's elements to the object's contents. Necessary for overloading the `+=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::addElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Add element method. Implements a method for adding data on the Harwell-Boeing matrix. Copy-pasted from writeElement.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
value Numerical type value.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::cleanBelow (const double factor) [inline], [virtual]
Clean below method. Makes equal to zero every element below given factor.
Parameters
factor Reference value for cleaning.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::clear () [inline], [virtual]
Clear method. Wipes all data. < Matrix data contents.
Implements lmx::Data< T >.
template<typename T > gmm::row_matrix< gmm::rsvector<T> >* lmx::Type_gmm_sparse< T >::data_pointer () [inline]
Data pointer method Gives the direction in memory of (pointer to) the object.
Returns
A pointer to the matrix's contents (Type_gmm_sparse).
Referenced by lmx::LinearSystem< T >::solveYourself().
template<typename T > void lmx::Type_gmm_sparse< T >::equals (const Data< T > * matrix_in) [inline], [virtual]
Copy method. Equals the data in the object's contents to those given by the input matrix parameter.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > bool lmx::Type_gmm_sparse< T >::exists (size_type , size_type) [inline], [virtual]
Returns TRUE or FALSE depending of element existance. Needed for less expensive access to CSC matrices.
Returns
TRUE if the element exists in internal storage structure.
Implements lmx::Data_mat< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::factorize (void) [inline], [virtual]
Implements lmx::Data_mat< T >.
template<typename T > size_type lmx::Type_gmm_sparse< T >::getCols () const [inline], [virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implements lmx::Data< T >.
template<typename T > size_type lmx::Type_gmm_sparse< T >::getRows () const [inline], [virtual]
Method for getting the number of data rows.
Returns
Number of rows.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::multiply (const Data< T > * matrix_in_1, const Data< T > * matrix_in_2) [inline], [virtual]
Multiply method. Multiplies the input matrices and saves the result into the object's contents. Necessary for overloading the `*` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
matrix_in_2 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data_mat< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::multiplyElements (const Data< T > * matrix_in) [inline], [virtual]
Method multiplying element-by-element of two matrices. One would be the object's contents and the other the parameter's contents. Necessary for implementing Vector to Vector multElements.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T > void lmx::Type_gmm_sparse< T >::multiplyScalar (const T & scalar) [inline], [virtual]
Multiply scalar method. Multiplies the object's matrix (contents) with a scalar. Necessary for overloading the `*` operator.
Parameters
scalar A scalar factor of template's class.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::read_hb_file (const char * input_file) [inline], [virtual]
Read data in Harwell-Boeing format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Harwell-Boeing format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
References lmx::copy().
template<typename T > void lmx::Type_gmm_sparse< T >::read_mm_file (const char * input_file) [inline], [virtual]
Read data in Matrix Market format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Matrix Market format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
References lmx::copy().
template<typename T > const T& lmx::Type_gmm_sparse< T >::readElement (const size_type & mrows, const size_type & ncolumns) const [inline], [virtual]
Read element method. Implements a method for reading data of the sparse matrix.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
Returns
Value of the element in the position given by the parameters.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::reset () [inline], [virtual]
Reset method. Resets all elements to 0.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::resize (size_type mrows, size_type ncolumns) [virtual]
Resize method. Changes the size of the contents parameter.
Parameters
mrows New value for rows of sparse matrix.
ncolumns New value for columns of sparse matrix.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::substract (const Data< T > * matrix_in_1) [inline], [virtual]
Substract method. Substracts the the input matrix parameter's elements to the object's contents. Necessary for overloading the `-=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_gmm_sparse< T >::trn () [inline], [virtual]
Traspose method. Swaps elements with respect to the diagonal: A(i,j) = A(j,i)
Implements lmx::Data_mat< T >.
References lmx::copy().
template<typename T > void lmx::Type_gmm_sparse< T >::write_hb_file (const char * input_file) [inline], [virtual]
Write data in Harwell-Boeing format method. Opens the file specified and writes the matrix's data in it.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
References lmx::copy().
template<typename T > void lmx::Type_gmm_sparse< T >::writeElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Write element method. Implements a method for writing data on the sparse matrix.
Parameters
mrows Row position in sparse matrix.
ncolumns Column position in sparse matrix.
value Numerical type value.
Implements lmx::Data< T >.
The documentation for this class was generated from the following file:
src/LMX/lmx_mat_type_gmm_sparse1.h