lmx::Configuration< T > Class Template Reference
Template class Configuration.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_diff_configuration.h>
Public Member Functions
Configuration ()
Configuration (double t_o)
~Configuration ()
void quiet ()
Needed to improve the output of DiffProblemFirstSecond runs.
void nextStep (double &stepSize)
double getTime (int step=0)
int getTimeSize ()
double getLastStepSize ()
const lmx::Vector< T > & getConf (int order, int step=0)
int getDiffOrder ()
void setTime (double &time_in)
void setInitialCondition (int diff_order, lmx::Vector< T > &q_o)
void setStoredSteps (int steps_q_o, int steps_q_i, int steps_q_n)
void setConf (int diff_order, Vector< T > values, int time_step=0)
Vector< T > & setConf (int diff_order, int time_step=0)
Detailed Description
template<class T>class lmx::Configuration< T >
Template class Configuration.
Basic variables, derivatives and time. The data is stored in the last steps, which number depends on integrator type.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<class T> lmx::Configuration< T >::Configuration () [inline]
Empty constructor.
template<class T> lmx::Configuration< T >::Configuration (double t_o) [inline]
Standard constructor.
Parameters
t_o Time at first step.
template<class T> lmx::Configuration< T >::~Configuration () [inline]
Destructor.
Member Function Documentation
template<class T> const lmx::Vector<T>& lmx::Configuration< T >::getConf (int order, int step = 0) [inline]
Parameters
order Differential order of configuration.
step Indicates the (actual - step) time step
Returns
The configuration of the diff-order and step specified.
template<class T> int lmx::Configuration< T >::getDiffOrder () [inline]
Returns
Maximum differential order of stored configuration.
template<class T> double lmx::Configuration< T >::getLastStepSize () [inline]
Returns
Value of last time increment.
template<class T> double lmx::Configuration< T >::getTime (int step = 0) [inline]
Parameters
step Indicates the (actual - step) time step.
Returns
The time value of the step.
template<class T> int lmx::Configuration< T >::getTimeSize () [inline]
Access to size of time line.
template<class T > void lmx::Configuration< T >::nextStep (double & step_size)
Reshapes storing vectors to the required dimension for last steps storage.
Parameters
step_size time increment between last and next step.
template<class T> void lmx::Configuration< T >::quiet () [inline]
Needed to improve the output of DiffProblemFirstSecond runs.
template<class T> void lmx::Configuration< T >::setConf (int diff_order, Vector< T > values, int time_step = 0) [inline]
Parameters
diff_order Differential order of configuration.
values Values of configuration to be set.
time_step Indicates the (actual - step) time step
template<class T> Vector<T>& lmx::Configuration< T >::setConf (int diff_order, int time_step = 0) [inline]
Parameters
diff_order Differential order of configuration.
time_step Indicates the (actual - step) time step
Returns
Values of configuration.
template<class T > void lmx::Configuration< T >::setInitialCondition (int diff_order, lmx::Vector< T > & q_o)
Parameters
diff_order Order of differential system.
q_o Value of initial condition to be set.
References LMX_THROW, and lmx::Vector< T >::size().
Referenced by lmx::DiffProblem< Sys, T >::setInitialConfiguration(), lmx::DiffProblemDouble< Sys, T >::setInitialConfiguration1(), and lmx::DiffProblemDouble< Sys, T >::setInitialConfiguration2().
template<class T > void lmx::Configuration< T >::setStoredSteps (int steps_q_o, int steps_q_i, int steps_q_n)
Reshapes storing vectors to the required dimension for last steps storage.
Parameters
steps_q_o Number of steps to store the basic variable.
steps_q_i Number of steps to store from first to (n-1) derivatives.
steps_q_n Number of steps to store the n derivative.
References LMX_THROW.
Referenced by lmx::IntegratorCentralDifference< T >::initialize(), lmx::IntegratorAB< T >::initialize(), lmx::IntegratorNEWMARK< T >::initialize(), lmx::IntegratorBDF< T >::initialize(), and lmx::IntegratorAM< T >::initialize().
template<class T> void lmx::Configuration< T >::setTime (double & time_in) [inline]
Sets the time of actual (last) time step.
Parameters
time_in Value of time to be set.
The documentation for this class was generated from the following file:
src/LMX/lmx_diff_configuration.h