lmx::DiffProblemDouble< Sys, T > Class Template Reference
Template class DiffProblemDouble. Implementation for ODE system solvers.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_diff_problem_double.h>
Public Member Functions
DiffProblemDouble ()
virtual ~DiffProblemDouble ()
void setDiffSystem (Sys &system_in)
void setIntegrator1 (int type, int opt1=0, int opt2=0)
void setIntegrator2 (int type, int opt1=0, int opt2=0)
void setIntegrator1 (const char *type, int opt2=0)
void setIntegrator2 (const char *type, int opt2=0)
void setInitialConfiguration1 (lmx::Vector< T > &q_o)
void setInitialConfiguration2 (lmx::Vector< T > &q_o, lmx::Vector< T > &qdot_o)
void setOutputFile1 (const char *filename, int diffOrder)
void setOutputFile2 (const char *filename, int diffOrder)
void setTimeParameters (double to_in, double tf_in, double step_size_in)
void setStepTriggered (void(Sys::*stepTriggered_in)())
void setConvergence (double eps_in)
const lmx::Vector< T > & getConfiguration1 (int order, int step=0)
const lmx::Vector< T > & getConfiguration2 (int order, int step=0)
bool isIntegratorExplicit ()
virtual void initialize ()=0
virtual void stepSolve ()=0
virtual void solve ()=0
Protected Member Functions
void writeStepFiles ()
Protected Attributes
lmx::NLSolverDouble< T > * theNLSolver
Pointer to the NLSolver object, (auto-created).
lmx::Configuration< T > * theConfiguration1
Pointer to the Configuration object, (auto-created).
lmx::Configuration< T > * theConfiguration2
Pointer to the Configuration object, (auto-created).
lmx::IntegratorBase< T > * theIntegrator1
Pointer to the Integrator object, (auto-created).
lmx::IntegratorBase< T > * theIntegrator2
Pointer to the Integrator object, (auto-created).
Sys * theSystem
Pointer to object where the differential system is defined.
lmx::Vector< T > * p_delta_q1
Stores pointer to NLSolver increment.
lmx::Vector< T > * p_delta_q2
Stores pointer to NLSolver increment.
bool b_steptriggered
1 if stepTriggered function is set.
double to
Value of the start time stored from input.
double tf
Value of the finish time stored from input.
double stepSize
Value of the time step stored from input.
double epsilon
Value for L2 convergence.
std::map< int, std::ofstream * > fileOutMap1
collection of output streams for each diff-order requested.
std::map< int, std::ofstream * > fileOutMap2
collection of output streams for each diff-order requested.
void(Sys::* stepTriggered)()
function called at the end of each time step
Detailed Description
template<typename Sys, typename T = double>class lmx::DiffProblemDouble< Sys, T >
Template class DiffProblemDouble. Implementation for ODE system solvers.
This class implements methods for defining and solving partitioned initial value problems described by a TotalDiff class' derivided object, and initial conditions in the form $ \dot{q}(t_o) = \dot{q}_o $, $ q(t_o) = q_o $.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename Sys , typename T = double> lmx::DiffProblemDouble< Sys, T >::DiffProblemDouble () [inline]
Empty constructor.
template<typename Sys , typename T = double> virtual lmx::DiffProblemDouble< Sys, T >::~DiffProblemDouble () [inline], [virtual]
Destructor.
Member Function Documentation
template<typename Sys , typename T = double> const lmx::Vector<T>& lmx::DiffProblemDouble< Sys, T >::getConfiguration1 (int order, int step = 0) [inline]
References lmx::DiffProblemDouble< Sys, T >::theConfiguration1.
template<typename Sys , typename T = double> const lmx::Vector<T>& lmx::DiffProblemDouble< Sys, T >::getConfiguration2 (int order, int step = 0) [inline]
References lmx::DiffProblemDouble< Sys, T >::theConfiguration2.
template<typename Sys , typename T = double> virtual void lmx::DiffProblemDouble< Sys, T >::initialize () [pure virtual]
Solve methods to be implemented in derived classes.
Implemented in lmx::DiffProblemFirstSecond< Sys, T >.
template<typename Sys , typename T = double> bool lmx::DiffProblemDouble< Sys, T >::isIntegratorExplicit () [inline]
References lmx::DiffProblemDouble< Sys, T >::theIntegrator1, and lmx::DiffProblemDouble< Sys, T >::theIntegrator2.
template<typename Sys , typename T = double> void lmx::DiffProblemDouble< Sys, T >::setConvergence (double eps_in) [inline]
References lmx::DiffProblemDouble< Sys, T >::epsilon.
Referenced by lmx::DiffProblemFirstSecond< Sys, T >::setConvergence().
template<typename Sys , typename T = double> void lmx::DiffProblemDouble< Sys, T >::setDiffSystem (Sys & system_in) [inline]
Parameters
system_in Object that defines the differential system equations.
References lmx::DiffProblemDouble< Sys, T >::theSystem.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setInitialConfiguration1 (lmx::Vector< T > & q_o)
Defines initial conditions for first order diff. problems.
Parameters
q_o Zero-order initial configuration.
References lmx::Configuration< T >::setInitialCondition().
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setInitialConfiguration2 (lmx::Vector< T > & q_o, lmx::Vector< T > & qdot_o)
Defines initial conditions for second order diff. problems.
Parameters
q_o Zero-order initial configuration.
qdot_o First-order initial configuration.
References lmx::Configuration< T >::setInitialCondition().
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setIntegrator1 (int type, int opt1 = 0, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator family to use.
opt1 Optional value for some integrators (usually specifies the order).
opt2 Optional value for some integrators.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setIntegrator1 (const char * type, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator to use.
opt2 Optional value for some integrators.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setIntegrator2 (int type, int opt1 = 0, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator family to use.
opt1 Optional value for some integrators (usually specifies the order).
opt2 Optional value for some integrators.
Referenced by lmx::DiffProblemFirstSecond< Sys, T >::setIntegrator2().
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setIntegrator2 (const char * type, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator to use.
opt2 Optional value for some integrators.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setOutputFile1 (const char * filename, int diffOrder)
Defines which variables to store, specifing the file name for each diff-order.
Parameters
filename Name of file for storing variables.
diffOrder
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setOutputFile2 (const char * filename, int diffOrder)
Defines which variables to store, specifing the file name for each diff-order.
Parameters
filename Name of file for storing variables.
diffOrder
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setStepTriggered (void(Sys::*)() stepTriggered_in)
Defines a function call between time steps.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::setTimeParameters (double to_in, double tf_in, double step_size_in)
Defines basic time parameters.
Parameters
to_in Initial time.
tf_in End time
step_size_in Prefered time step.
template<typename Sys , typename T = double> virtual void lmx::DiffProblemDouble< Sys, T >::solve () [pure virtual]
Implemented in lmx::DiffProblemFirstSecond< Sys, T >.
template<typename Sys , typename T = double> virtual void lmx::DiffProblemDouble< Sys, T >::stepSolve () [pure virtual]
Implemented in lmx::DiffProblemFirstSecond< Sys, T >.
template<typename Sys , typename T > void lmx::DiffProblemDouble< Sys, T >::writeStepFiles () [protected]
When the configuration advances, this method is invoked for writing the requested diff-order values.
Member Data Documentation
template<typename Sys , typename T = double> bool lmx::DiffProblemDouble< Sys, T >::b_steptriggered [protected]
1 if stepTriggered function is set.
template<typename Sys , typename T = double> double lmx::DiffProblemDouble< Sys, T >::epsilon [protected]
Value for L2 convergence.
Referenced by lmx::DiffProblemDouble< Sys, T >::setConvergence().
template<typename Sys , typename T = double> std::map<int, std::ofstream *> lmx::DiffProblemDouble< Sys, T >::fileOutMap1 [protected]
collection of output streams for each diff-order requested.
template<typename Sys , typename T = double> std::map<int, std::ofstream *> lmx::DiffProblemDouble< Sys, T >::fileOutMap2 [protected]
collection of output streams for each diff-order requested.
template<typename Sys , typename T = double> lmx::Vector<T>* lmx::DiffProblemDouble< Sys, T >::p_delta_q1 [protected]
Stores pointer to NLSolver increment.
Referenced by lmx::DiffProblemFirstSecond< Sys, T >::~DiffProblemFirstSecond().
template<typename Sys , typename T = double> lmx::Vector<T>* lmx::DiffProblemDouble< Sys, T >::p_delta_q2 [protected]
Stores pointer to NLSolver increment.
Referenced by lmx::DiffProblemFirstSecond< Sys, T >::~DiffProblemFirstSecond().
template<typename Sys , typename T = double> double lmx::DiffProblemDouble< Sys, T >::stepSize [protected]
Value of the time step stored from input.
template<typename Sys , typename T = double> void(Sys::* lmx::DiffProblemDouble< Sys, T >::stepTriggered)() [protected]
function called at the end of each time step
template<typename Sys , typename T = double> double lmx::DiffProblemDouble< Sys, T >::tf [protected]
Value of the finish time stored from input.
template<typename Sys , typename T = double> lmx::Configuration<T>* lmx::DiffProblemDouble< Sys, T >::theConfiguration1 [protected]
Pointer to the Configuration object, (auto-created).
Referenced by lmx::DiffProblemDouble< Sys, T >::getConfiguration1().
template<typename Sys , typename T = double> lmx::Configuration<T>* lmx::DiffProblemDouble< Sys, T >::theConfiguration2 [protected]
Pointer to the Configuration object, (auto-created).
Referenced by lmx::DiffProblemDouble< Sys, T >::getConfiguration2().
template<typename Sys , typename T = double> lmx::IntegratorBase<T>* lmx::DiffProblemDouble< Sys, T >::theIntegrator1 [protected]
Pointer to the Integrator object, (auto-created).
Referenced by lmx::DiffProblemDouble< Sys, T >::isIntegratorExplicit().
template<typename Sys , typename T = double> lmx::IntegratorBase<T>* lmx::DiffProblemDouble< Sys, T >::theIntegrator2 [protected]
Pointer to the Integrator object, (auto-created).
Referenced by lmx::DiffProblemDouble< Sys, T >::isIntegratorExplicit().
template<typename Sys , typename T = double> lmx::NLSolverDouble<T>* lmx::DiffProblemDouble< Sys, T >::theNLSolver [protected]
Pointer to the NLSolver object, (auto-created).
template<typename Sys , typename T = double> Sys* lmx::DiffProblemDouble< Sys, T >::theSystem [protected]
Pointer to object where the differential system is defined.
Referenced by lmx::DiffProblemDouble< Sys, T >::setDiffSystem().
template<typename Sys , typename T = double> double lmx::DiffProblemDouble< Sys, T >::to [protected]
Value of the start time stored from input.
The documentation for this class was generated from the following file:
src/LMX/lmx_diff_problem_double.h