lmx::DiffProblem< Sys, T > Class Template Reference
Template class DiffProblem. Implementation for ODE system solvers.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_diff_problem.h>
Public Member Functions
DiffProblem ()
virtual ~DiffProblem ()
void setDiffSystem (Sys &system_in)
void setIntegrator (int type, int opt1=0, int opt2=0)
void setIntegrator (const std::string &type, int opt2=0)
void setInitialConfiguration (lmx::Vector< T > &q_o)
void setInitialConfiguration (lmx::Vector< T > &q_o, lmx::Vector< T > &qdot_o)
void setOutputFile (const char *filename, int diffOrder)
void setTimeParameters (double to_in, double tf_in, double step_size_in)
void iterationResidue (lmx::Vector< T > &residue, lmx::Vector< T > &q_actual)
void setStepTriggered (void(Sys::*stepTriggered_in)())
void setConvergence (double eps_in)
const lmx::Vector< T > & getConfiguration (int order, int step=0)
bool isIntegratorExplicit ()
void setVervosity (int level)
virtual void initialize ()=0
virtual void stepSolve ()=0
virtual void solve ()=0
void advance ()
Advances the configuration and the integrator without solving the system.
Protected Member Functions
void writeStepFiles ()
Protected Attributes
lmx::Configuration< T > * theConfiguration
Pointer to the Configuration object, (auto-created).
lmx::IntegratorBase< T > * theIntegrator
Pointer to the Integrator object, (auto-created).
lmx::NLSolver< T > * theNLSolver
Pointer to the NLSolver object, (auto-created).
Sys * theSystem
Pointer to object where the differential system is defined.
lmx::Vector< T > * p_delta_q
Stores pointer to NLSolver increment.
bool b_steptriggered
1 if stepTriggered function is set.
double to
Value of the start time stored from input.
double tf
Value of the finish time stored from input.
double stepSize
Value of the time step stored from input.
double epsilon
Value for L2 convergence.
std::map< int, std::ofstream * > fileOutMap
collection of output streams for each diff-order requested.
void(Sys::* stepTriggered)()
function called at the end of each time step
int vervosity
Detailed Description
template<typename Sys, typename T = double>class lmx::DiffProblem< Sys, T >
Template class DiffProblem. Implementation for ODE system solvers.
This class implements methods for defining and solving initial value problems described by a TotalDiff class' derivided object, and initial conditions in the form $ \dot{q}(t_o) = \dot{q}_o $, $ q(t_o) = q_o $.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename Sys , typename T = double> lmx::DiffProblem< Sys, T >::DiffProblem () [inline]
Empty constructor.
template<typename Sys , typename T = double> virtual lmx::DiffProblem< Sys, T >::~DiffProblem () [inline], [virtual]
Destructor.
References lmx::DiffProblem< Sys, T >::theConfiguration, and lmx::DiffProblem< Sys, T >::theIntegrator.
Member Function Documentation
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::advance ()
Advances the configuration and the integrator without solving the system.
Advances the configuration and the integrator without solving the system.
template<typename Sys , typename T = double> const lmx::Vector<T>& lmx::DiffProblem< Sys, T >::getConfiguration (int order, int step = 0) [inline]
References lmx::DiffProblem< Sys, T >::theConfiguration.
template<typename Sys , typename T = double> virtual void lmx::DiffProblem< Sys, T >::initialize () [pure virtual]
Solve method to be implemented in derived classes.
Implemented in lmx::DiffProblemSecond< Sys, T >, and lmx::DiffProblemFirst< Sys, T >.
template<typename Sys , typename T = double> bool lmx::DiffProblem< Sys, T >::isIntegratorExplicit () [inline]
References lmx::DiffProblem< Sys, T >::theIntegrator.
template<typename Sys , typename T = double> void lmx::DiffProblem< Sys, T >::iterationResidue (lmx::Vector< T > & residue, lmx::Vector< T > & q_actual)
template<typename Sys , typename T = double> void lmx::DiffProblem< Sys, T >::setConvergence (double eps_in) [inline]
References lmx::DiffProblem< Sys, T >::epsilon.
Referenced by lmx::DiffProblemFirst< Sys, T >::setConvergence(), and lmx::DiffProblemSecond< Sys, T >::setConvergence().
template<typename Sys , typename T = double> void lmx::DiffProblem< Sys, T >::setDiffSystem (Sys & system_in) [inline]
Parameters
system_in Object that defines the differential system equations.
References lmx::DiffProblem< Sys, T >::theSystem.
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setInitialConfiguration (lmx::Vector< T > & q_o)
Defines initial conditions for first order diff. problems.
Parameters
q_o Zero-order initial configuration.
References lmx::Configuration< T >::setInitialCondition().
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setInitialConfiguration (lmx::Vector< T > & q_o, lmx::Vector< T > & qdot_o)
Defines initial conditions for second order diff. problems.
Parameters
q_o Zero-order initial configuration.
qdot_o First-order initial configuration.
References lmx::Configuration< T >::setInitialCondition().
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setIntegrator (int type, int opt1 = 0, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator family to use.
opt1 Optional value for some integrators (usually specifies the order).
opt2 Optional value for some integrators.
Referenced by lmx::DiffProblemSecond< Sys, T >::setIntegrator().
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setIntegrator (const std::string & type, int opt2 = 0)
Defines the integrator that will be used for configuration advance & actualization.
Parameters
type Key of integrator to use.
opt2 Optional value for some integrators.
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setOutputFile (const char * filename, int diffOrder)
Defines which variables to store, specifing the file name for each diff-order.
Parameters
filename Name of file for storing variables.
diffOrder
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setStepTriggered (void(Sys::*)() stepTriggered_in)
Defines a function call between time steps.
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::setTimeParameters (double to_in, double tf_in, double step_size_in)
Defines basic time parameters.
Parameters
to_in Initial time.
tf_in End time
step_size_in Prefered time step.
template<typename Sys , typename T = double> void lmx::DiffProblem< Sys, T >::setVervosity (int level) [inline]
References lmx::DiffProblem< Sys, T >::vervosity.
template<typename Sys , typename T = double> virtual void lmx::DiffProblem< Sys, T >::solve () [pure virtual]
Implemented in lmx::DiffProblemSecond< Sys, T >, and lmx::DiffProblemFirst< Sys, T >.
template<typename Sys , typename T = double> virtual void lmx::DiffProblem< Sys, T >::stepSolve () [pure virtual]
Implemented in lmx::DiffProblemSecond< Sys, T >, and lmx::DiffProblemFirst< Sys, T >.
template<typename Sys , typename T > void lmx::DiffProblem< Sys, T >::writeStepFiles () [protected]
When the configuration advances, this method is invoked for writing the requested diff-order values.
Member Data Documentation
template<typename Sys , typename T = double> bool lmx::DiffProblem< Sys, T >::b_steptriggered [protected]
1 if stepTriggered function is set.
template<typename Sys , typename T = double> double lmx::DiffProblem< Sys, T >::epsilon [protected]
Value for L2 convergence.
Referenced by lmx::DiffProblem< Sys, T >::setConvergence().
template<typename Sys , typename T = double> std::map<int, std::ofstream *> lmx::DiffProblem< Sys, T >::fileOutMap [protected]
collection of output streams for each diff-order requested.
template<typename Sys , typename T = double> lmx::Vector<T>* lmx::DiffProblem< Sys, T >::p_delta_q [protected]
Stores pointer to NLSolver increment.
Referenced by lmx::DiffProblemSecond< Sys, T >::~DiffProblemSecond().
template<typename Sys , typename T = double> double lmx::DiffProblem< Sys, T >::stepSize [protected]
Value of the time step stored from input.
template<typename Sys , typename T = double> void(Sys::* lmx::DiffProblem< Sys, T >::stepTriggered)() [protected]
function called at the end of each time step
template<typename Sys , typename T = double> double lmx::DiffProblem< Sys, T >::tf [protected]
Value of the finish time stored from input.
template<typename Sys , typename T = double> lmx::Configuration<T>* lmx::DiffProblem< Sys, T >::theConfiguration [protected]
Pointer to the Configuration object, (auto-created).
Referenced by lmx::DiffProblem< Sys, T >::getConfiguration(), and lmx::DiffProblem< Sys, T >::~DiffProblem().
template<typename Sys , typename T = double> lmx::IntegratorBase<T>* lmx::DiffProblem< Sys, T >::theIntegrator [protected]
Pointer to the Integrator object, (auto-created).
Referenced by lmx::DiffProblem< Sys, T >::isIntegratorExplicit(), and lmx::DiffProblem< Sys, T >::~DiffProblem().
template<typename Sys , typename T = double> lmx::NLSolver<T>* lmx::DiffProblem< Sys, T >::theNLSolver [protected]
Pointer to the NLSolver object, (auto-created).
template<typename Sys , typename T = double> Sys* lmx::DiffProblem< Sys, T >::theSystem [protected]
Pointer to object where the differential system is defined.
Referenced by lmx::DiffProblem< Sys, T >::setDiffSystem().
template<typename Sys , typename T = double> double lmx::DiffProblem< Sys, T >::to [protected]
Value of the start time stored from input.
template<typename Sys , typename T = double> int lmx::DiffProblem< Sys, T >::vervosity [protected]
Referenced by lmx::DiffProblem< Sys, T >::setVervosity().
The documentation for this class was generated from the following file:
src/LMX/lmx_diff_problem.h