lmx::Type_stdVector< T > Class Template Reference
Template class Type_stdVector.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_data_blas.h>
Public Member Functions
Type_stdVector ()
Empty constructor.
Type_stdVector (size_type, size_type)
Type_stdVector (char *)
~Type_stdVector ()
Destructor.
void resize (size_type mrows, size_type ncolumns)
const T & readElement (const size_type &mrows, const size_type &ncolumns) const
void writeElement (T value, const size_type &mrows, const size_type &ncolumns)
void addElement (T value, const size_type &mrows, const size_type &ncolumns)
size_type getRows () const
size_type getCols () const
void equals (const Data< T > *vector_in)
void add (const Data< T > *vector_in_1)
void substract (const Data< T > *vector_in_1)
void multiplyScalar (const T &scalar)
void multiplyElements (const Data< T > *vector_in)
void cleanBelow (const double factor)
void readDataFile (const char *input_file)
void writeDataFile (const char *output_file)
void clear ()
void reset ()
std::vector< T > * data_pointer ()
Friends
void mat_vec_mult (const Type_csc< T > *, const Type_stdVector< T > *, Type_stdVector< T > *)
Detailed Description
template<typename T>class lmx::Type_stdVector< T >
Template class Type_stdVector.
This class implements the methods defined in virtual class data_mat so the Vector type `std::vector` can be used in lmx. For details about the caracteristics of this matrix type, see the STL library manual and code.
Parameters
contents Corresponds to a std::vector and it's the base of the methods implemented for this class.
Author
Daniel Iglesias .
Constructor & Destructor Documentation
template<typename T> lmx::Type_stdVector< T >::Type_stdVector () [inline]
Empty constructor.
template<typename T > lmx::Type_stdVector< T >::Type_stdVector (size_type rows, size_type columns)
Standard constructor.
Creates a new object with parameter contents resized to (columns) dimension.
Parameters
rows Rows of dense stdVector.
columns Not used.
Returns
template<typename T > lmx::Type_stdVector< T >::Type_stdVector (char * input_file)
Constructor from a data file. Creates a new object reading data from a file.
Parameters
input_file Name of file to read from.
References lmx::Type_stdVector< T >::readDataFile().
template<typename T> lmx::Type_stdVector< T >::~Type_stdVector () [inline]
Destructor.
Member Function Documentation
template<typename T> void lmx::Type_stdVector< T >::add (const Data< T > * vector_in_1) [inline], [virtual]
Add method. Adds the the input vector parameter's elements to the object's contents. Necessary for overloading the `+=` operator.
Parameters
vector_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::addElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Add element method. Implements a method for adding data on the Harwell-Boeing matrix. Copy-pasted from writeElement.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
value Numerical type value.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::cleanBelow (const double) [inline], [virtual]
Method for cleaning all elements below a given factor.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::clear () [inline], [virtual]
Clear method. Wipes all data.
Implements lmx::Data< T >.
template<typename T> std::vector<T>* lmx::Type_stdVector< T >::data_pointer () [inline]
Data pointer method Gives the direction in memory of (pointer to) the object.
Returns
A pointer to the vector's contents (Type_stdVector).
Referenced by lmx::LinearSystem< T >::initSLU(), lmx::LinearSystem< T >::setb(), lmx::LinearSystem< T >::solveYourself(), and lmx::LinearSystem< T >::subsSolve().
template<typename T> void lmx::Type_stdVector< T >::equals (const Data< T > * vector_in) [inline], [virtual]
Copy method. Equals the data in the object's contents to those given by the input vector's parameter.
Parameters
vector_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> size_type lmx::Type_stdVector< T >::getCols () const [inline], [virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implements lmx::Data< T >.
template<typename T> size_type lmx::Type_stdVector< T >::getRows () const [inline], [virtual]
Method for knowing the number of data rows.
Returns
Number of rows.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::multiplyElements (const Data< T > * vector_in) [inline], [virtual]
Method multiplying element-by-element of two arrays. One would be the object's contents and the other the parameter's contents. Necessary for implementing Vector to Vector multElements.
Parameters
vector_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T> void lmx::Type_stdVector< T >::multiplyScalar (const T & scalar) [inline], [virtual]
Multiply scalar method. Multiplies the object's vector (contents) with a scalar. Necessary for overloading the `*` operator.
Parameters
scalar A scalar factor of template's class.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::readDataFile (const char * input_file) [inline], [virtual]
Read data method. Opens the file specified and reads the vector's data in it.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_vec< T >.
References lmx::Type_stdVector< T >::resize().
Referenced by lmx::Type_stdVector< T >::Type_stdVector().
template<typename T> const T& lmx::Type_stdVector< T >::readElement (const size_type & mrows, const size_type & ncolumns) const [inline], [virtual]
Read element method. Implements a method for reading vector's data.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
Returns
Value of the element in the position given by the parameter.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::reset () [inline], [virtual]
Reset method.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::resize (size_type mrows, size_type ncolumns) [inline], [virtual]
Resize method. Changes the size of the contents parameter.
Parameters
mrows New value for vector's size.
ncolumns Not used.
Implements lmx::Data< T >.
Referenced by lmx::Type_stdVector< T >::readDataFile().
template<typename T> void lmx::Type_stdVector< T >::substract (const Data< T > * vector_in_1) [inline], [virtual]
Substract method. Substracts the the input vector parameter's elements to the object's contents. Necessary for overloading the `-=` operator.
Parameters
vector_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdVector< T >::writeDataFile (const char * output_file) [inline], [virtual]
Write data method. Opens the file specified and writes the vector's data in it.
Parameters
output_file Name of the file to be read.
Implements lmx::Data_vec< T >.
template<typename T> void lmx::Type_stdVector< T >::writeElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Write element method. Implements a method for writing data on the dense matrix.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
value Numerical type value.
Implements lmx::Data< T >.
Friends And Related Function Documentation
template<typename T> void mat_vec_mult (const Type_csc< T > * matrix_in, const Type_stdVector< T > * vector_in, Type_stdVector< T > * vector_out) [friend]
Matrix vector (pre)multiplication, specialized for Type_csc Data_mat (matrix) and Type_stdVector (STL vector) formats. Calculates the product A*b = c using pointers.
Parameters
matrix_in Type_csc *Matrix A.
vector_in Type_stdVector *Vector b.
vector_out Type_stdVector *Vector c = A*b.
The documentation for this class was generated from the following files:
src/LMX/lmx_mat_data_blas.h
src/LMX/lmx_mat_type_stdvector.h