Simulation Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/simulation.h>
Public Member Functions
Simulation ()
~Simulation ()
void read (char *)
void compute ()
void output ()
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Simulation::Simulation ()
Simulation::~Simulation ()
Member Function Documentation
void Simulation::compute ()
Referenced by main().
void Simulation::output ()
Referenced by main().
void Simulation::read (char * file_name)
Referenced by main().
The documentation for this class was generated from the following files:
src/simulation.h
src/simulation.cpp