cofe::TensorRank2< Dim, T > Class Template Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/cofe_TensorRank1.h>
Public Types
typedef T scalar_type
typedef cofe::TensorRank1< Dim, T > vector_type
typedef cofe::TensorRank2< Dim, T > tensor_type
typedef cofe::TensorRank2< Dim, T > own_type
typedef
*
cofe::AbstractTensorRank4SS
*
< Dim, T > ar4tensor_type
Public Member Functions
TensorRank2 ()
TensorRank2 (const T ptr[Dim][Dim])
TensorRank2 (const T &aValue)
TensorRank2 (const std::string &stringOfComponents)
TensorRank2 (const char *c_stringOfComponents)
TensorRank2 (const own_type &aTen)
virtual ~TensorRank2 ()
bool initializeFrom (const std::string &s)
bool initializeFrom (std::istream &istre)
int size ()
scalar_type & operator() (int i, int j)
const scalar_type & operator() (int i, int j) const
scalar_type trace () const
tensor_type & operator= (const T &aValue)
tensor_type & operator= (const std::string &stringOfComponents)
tensor_type & operator= (const char *c_stringOfComponents)
tensor_type & operator= (const tensor_type &aTen)
void zero ()
void operator*= (const scalar_type aValue)
void operator+= (const TensorRank2< Dim, T > a)
void operator-= (const TensorRank2< Dim, T > a)
scalar_type dot (const tensor_type &aTensor) const
void operateOn (const vector_type &operand, vector_type &answer) const
void beTransposeOf (const tensor_type &Ten)
void beProductOf (const vector_type &leftVec, const ar4tensor_type &r4T, const vector_type &rightVec)
void beProductOf (const vector_type &leftVec, const vector_type &rightVec)
void beProductOf (const tensor_type &leftTen, const tensor_type &rightTen)
void beTraProductOf (const tensor_type &leftTen, const tensor_type &rightTen)
void beProductTraOf (const tensor_type &leftTen, const tensor_type &rightTen)
void beUnityTensor ()
void solve (const vector_type &operand, vector_type &answer) const
void beInverseOf (const tensor_type &atensor)
scalar_type determinant () const
scalar_type secondInvariant () const
TensorRank2 (const int &aValue)
std::ostream & print_row (std::ostream &, const cofe::TensorRank2< Dim, T > &, int) const
bool operator== (const T &aValue) const
bool operator!= (const T &aValue) const
void operator*= (const own_type aTensor)
operator T ()
template<>
double determinant () const
template<>
double determinant () const
template<>
void solve (const cofe::TensorRank1< 2, double > &rh, cofe::TensorRank1< 2, double > &lh) const
template<>
void beInverseOf (const cofe::TensorRank2< 2, double > &aT)
template<>
void beInverseOf (const cofe::TensorRank2< 3, double > &T)
Protected Attributes
scalar_type com [Dim][Dim]
Friends
class TensorRank1< Dim, T >
own_type operator* (const own_type &T1, const own_type &T2)
Member Typedef Documentation
template<int Dim, class T> typedef cofe::AbstractTensorRank4SS<Dim, T> cofe::TensorRank2< Dim, T >::ar4tensor_type
template<int Dim, class T> typedef cofe::TensorRank2<Dim,T> cofe::TensorRank2< Dim, T >::own_type
template<int Dim, class T> typedef T cofe::TensorRank2< Dim, T >::scalar_type
template<int Dim, class T> typedef cofe::TensorRank2<Dim,T> cofe::TensorRank2< Dim, T >::tensor_type
template<int Dim, class T> typedef cofe::TensorRank1<Dim,T> cofe::TensorRank2< Dim, T >::vector_type
Constructor & Destructor Documentation
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 () [inline]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const T ptr[Dim][Dim]) [inline]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const T & aValue) [inline]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const std::string & stringOfComponents) [inline]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const char * c_stringOfComponents) [inline]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const own_type & aTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > cofe::TensorRank2< Dim, T >::~TensorRank2 () [inline], [virtual]
template<int Dim, class T > cofe::TensorRank2< Dim, T >::TensorRank2 (const int & aValue) [inline]
Member Function Documentation
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beInverseOf (const tensor_type & atensor) [inline]
template<> void cofe::TensorRank2< 2, double >::beInverseOf (const cofe::TensorRank2< 2, double > & aT) [inline]
template<> void cofe::TensorRank2< 3, double >::beInverseOf (const cofe::TensorRank2< 3, double > & T) [inline]
References cofe::TensorRank2< Dim, T >::determinant(), and cofe::CofeUtils::error().
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beProductOf (const vector_type & leftVec, const ar4tensor_type & r4T, const vector_type & rightVec) [inline]
Referenced by operator*().
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beProductOf (const vector_type & leftVec, const vector_type & rightVec) [inline]
References cofe::TensorRank1< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beProductOf (const tensor_type & leftTen, const tensor_type & rightTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beProductTraOf (const tensor_type & leftTen, const tensor_type & rightTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beTransposeOf (const tensor_type & Ten) [inline]
References cofe::TensorRank2< Dim, T >::com.
Referenced by transposeOf().
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beTraProductOf (const tensor_type & leftTen, const tensor_type & rightTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::beUnityTensor () [inline]
Referenced by cofe::TensorRank2Sym< Dim, T >::beHydrostaticPartOf().
template<int Dim, class T > T cofe::TensorRank2< Dim, T >::determinant () const [inline]
Referenced by cofe::TensorRank2< Dim, T >::beInverseOf(), and inverseOf().
template<> double cofe::TensorRank2< 2, double >::determinant () const [inline]
template<> double cofe::TensorRank2< 3, double >::determinant () const [inline]
template<int Dim, class T > T cofe::TensorRank2< Dim, T >::dot (const tensor_type & aTensor) const [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > bool cofe::TensorRank2< Dim, T >::initializeFrom (const std::string & s) [inline]
template<int Dim, class T > bool cofe::TensorRank2< Dim, T >::initializeFrom (std::istream & istre) [inline]
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::operateOn (const vector_type & operand, vector_type & answer) const [inline]
References cofe::TensorRank1< Dim, T >::com.
Referenced by cofe::TensorRank1< Dim, T >::beProductOf().
template<int Dim, class T> cofe::TensorRank2< Dim, T >::operator T () [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T> bool cofe::TensorRank2< Dim, T >::operator!= (const T & aValue) const [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > T & cofe::TensorRank2< Dim, T >::operator() (int i, int j) [inline]
template<int Dim, class T > const T & cofe::TensorRank2< Dim, T >::operator() (int i, int j) const [inline]
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::operator*= (const scalar_type aValue) [inline]
template<int Dim, class T> void cofe::TensorRank2< Dim, T >::operator*= (const own_type aTensor) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::operator+= (const TensorRank2< Dim, T > a) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::operator-= (const TensorRank2< Dim, T > a) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > TensorRank2< Dim, T > & cofe::TensorRank2< Dim, T >::operator= (const T & aValue) [inline]
Referenced by cofe::TensorRank2Sym< Dim, T >::operator=().
template<int Dim, class T > TensorRank2< Dim, T > & cofe::TensorRank2< Dim, T >::operator= (const std::string & stringOfComponents) [inline]
template<int Dim, class T > TensorRank2< Dim, T > & cofe::TensorRank2< Dim, T >::operator= (const char * c_stringOfComponents) [inline]
template<int Dim, class T > TensorRank2< Dim, T > & cofe::TensorRank2< Dim, T >::operator= (const tensor_type & aTen) [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T> bool cofe::TensorRank2< Dim, T >::operator== (const T & aValue) const [inline]
References cofe::TensorRank2< Dim, T >::com.
template<int Dim, class T > std::ostream & cofe::TensorRank2< Dim, T >::print_row (std::ostream & os, const cofe::TensorRank2< Dim, T > & a, int row) const
template<int Dim, typename T > T cofe::TensorRank2< Dim, T >::secondInvariant () const [inline]
template<int Dim, class T > int cofe::TensorRank2< Dim, T >::size () [inline]
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::solve (const vector_type & operand, vector_type & answer) const [inline]
References cofe::TensorRank1< Dim, T >::com, cofe::TensorRank2< Dim, T >::com, and cofe::gausselim().
Referenced by cofe::TensorRank1< Dim, T >::beSolutionOf().
template<> void cofe::TensorRank2< 2, double >::solve (const cofe::TensorRank1< 2, double > & rh, cofe::TensorRank1< 2, double > & lh) const [inline]
template<int Dim, class T > T cofe::TensorRank2< Dim, T >::trace () const [inline]
Referenced by cofe::TensorRank2Sym< Dim, T >::beHydrostaticPartOf().
template<int Dim, class T > void cofe::TensorRank2< Dim, T >::zero () [inline]
Friends And Related Function Documentation
template<int Dim, class T> own_type operator* (const own_type & T1, const own_type & T2) [friend]
template<int Dim, class T> friend class TensorRank1< Dim, T > [friend]
Member Data Documentation
template<int Dim, class T> scalar_type cofe::TensorRank2< Dim, T >::com[Dim][Dim] [protected]
Referenced by cofe::TensorRank2< Dim, T >::beProductOf(), cofe::TensorRank2< Dim, T >::beProductTraOf(), cofe::TensorRank2Sym< Dim, T >::beSymmetricPartOf(), cofe::TensorRank2Sym< Dim, T >::beSymProductOf(), cofe::TensorRank2< Dim, T >::beTransposeOf(), cofe::TensorRank2< Dim, T >::beTraProductOf(), cofe::TensorRank2Sym< Dim, T >::checkSymmetry(), cofe::TensorRank2Sym< Dim, T >::computeMaxPrincipalDirection(), cofe::TensorRank2< Dim, T >::dot(), cofe::TensorRank2< Dim, T >::operator T(), cofe::TensorRank2< Dim, T >::operator!=(), cofe::TensorRank2< Dim, T >::operator*=(), cofe::TensorRank2< Dim, T >::operator+=(), cofe::TensorRank2< Dim, T >::operator-=(), cofe::TensorRank2< Dim, T >::operator=(), cofe::TensorRank2Sym< Dim, T >::operator=(), cofe::TensorRank2< Dim, T >::operator==(), cofe::TensorRank2< Dim, T >::solve(), cofe::TensorRank2< Dim, T >::TensorRank2(), and cofe::TensorRank2Sym< Dim, T >::TensorRank2Sym().
The documentation for this class was generated from the following files:
src/LMX/cofe_TensorRank1.h
src/LMX/cofe_TensorRank2.h