lmx::Cg< T > Class Template Reference
Template class Cg. This class implements the conjugate gradient iterative linear solver, with and without preconditioner. It uses LMX matrix and vector facilities so any kind of linked object can be used.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_linsolvers_cg.h>
Public Member Functions
Cg (Matrix< T > *, Vector< T > *)
~Cg ()
Vector< T > solve (int)
void precond ()
Detailed Description
template<typename T>class lmx::Cg< T >
Template class Cg. This class implements the conjugate gradient iterative linear solver, with and without preconditioner. It uses LMX matrix and vector facilities so any kind of linked object can be used.
Author
Roberto Ortega Aguilera, Juan C. García Orden.
Constructor & Destructor Documentation
template<typename T > lmx::Cg< T >::Cg (Matrix< T > * A_in, Vector< T > * b_in)
Standard constructor.
Parameters
A_in LHS Matrix
b_in RHS Vector
template<typename T > lmx::Cg< T >::~Cg ()
Destructor
Member Function Documentation
template<typename T > void lmx::Cg< T >::precond ()
Preconditioner function.
Referenced by lmx::LinearSystem< T >::solveYourself().
template<typename T > Vector< T > lmx::Cg< T >::solve (int info)
Solver function
Parameters
info output iteration information
Returns
References lmx::Vector< T >::add(), lmx::Vector< T >::mult(), lmx::Vector< T >::multElements(), and lmx::Vector< T >::subs().
Referenced by lmx::LinearSystem< T >::solveYourself().
The documentation for this class was generated from the following file:
src/LMX/lmx_linsolvers_cg.h