lmx::Type_stdmatrix< T > Class Template Reference
Template class Type_stdmatrix.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_data_blas.h>
Public Member Functions
Type_stdmatrix ()
Empty constructor.
Type_stdmatrix (size_type, size_type)
~Type_stdmatrix ()
Destructor.
void factorize ()
void resize (size_type, size_type)
const T & readElement (const size_type &mrows, const size_type &ncolumns) const
void writeElement (T value, const size_type &mrows, const size_type &ncolumns)
void addElement (T value, const size_type &mrows, const size_type &ncolumns)
size_type getRows () const
size_type getCols () const
void equals (const Data< T > *matrix_in)
void add (const Data< T > *matrix_in_1)
void substract (const Data< T > *matrix_in_1)
void multiply (const Data< T > *matrix_in_1, const Data< T > *matrix_in_2)
void multiplyScalar (const T &scalar)
void multiplyElements (const Data< T > *matrix_in)
void read_mm_file (const char *input_file)
void read_hb_file (const char *input_file)
void write_hb_file (const char *input_file)
void trn ()
void cleanBelow (const double factor)
void clear ()
void reset ()
std::vector< std::vector< T > > * data_pointer ()
bool exists (size_type, size_type)
Friends
class DenseMatrix< T >
void copy (const Type_stdmatrix< T > *, Type_csc< T > *)
Detailed Description
template<typename T>class lmx::Type_stdmatrix< T >
Template class Type_stdmatrix.
This class implements the methods defined in virtual class data_mat for dense matrix built with std vectors.
Parameters
contents Corresponds to a type std::vector< std::vector<T> >.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename T> lmx::Type_stdmatrix< T >::Type_stdmatrix () [inline]
Empty constructor.
template<typename T > lmx::Type_stdmatrix< T >::Type_stdmatrix (size_type rows_in, size_type columns_in)
Standard constructor. Creates a new object with parameter contents resized to (rows, columns) dimension.
Parameters
rows_in Rows of dense matrix.
columns_in Columns of dense matrix.
References lmx::Type_stdmatrix< T >::resize().
template<typename T> lmx::Type_stdmatrix< T >::~Type_stdmatrix () [inline]
Destructor.
Member Function Documentation
template<typename T> void lmx::Type_stdmatrix< T >::add (const Data< T > * matrix_in_1) [inline], [virtual]
Add method. Adds the the input matrix parameter's elements to the object's contents. Necessary for overloading the `+=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::addElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Add element method. Implements a method for adding data on the Harwell-Boeing matrix. Copy-pasted from writeElement.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
value Numerical type value.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::cleanBelow (const double factor) [inline], [virtual]
Clean below method. Makes equal to zero every element below given factor.
Parameters
factor Reference value for cleaning.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::clear () [inline], [virtual]
Clear method. Wipes all data.
Implements lmx::Data< T >.
template<typename T> std::vector<std::vector<T> >* lmx::Type_stdmatrix< T >::data_pointer () [inline]
Data pointer method Gives the direction in memory of (pointer to) the object.
Returns
A pointer to the matrix's contents (Type_stdmatrix).
template<typename T> void lmx::Type_stdmatrix< T >::equals (const Data< T > * matrix_in) [inline], [virtual]
Copy method. Equals the data in the object's contents to those given by the input matrix parameter.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> bool lmx::Type_stdmatrix< T >::exists (size_type , size_type) [inline], [virtual]
Returns TRUE or FALSE depending of element existance. Needed for less expensive access to CSC matrices.
Returns
TRUE if the element exists in internal storage structure.
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_stdmatrix< T >::factorize (void) [inline], [virtual]
Implements lmx::Data_mat< T >.
template<typename T> size_type lmx::Type_stdmatrix< T >::getCols () const [inline], [virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implements lmx::Data< T >.
template<typename T> size_type lmx::Type_stdmatrix< T >::getRows () const [inline], [virtual]
Method for knowing the number of data rows.
Returns
Number of rows.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::multiply (const Data< T > * matrix_in_1, const Data< T > * matrix_in_2) [inline], [virtual]
Multiply method. Multiplies the input matrices and saves the result into the object's contents. Necessary for overloading the `*` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
matrix_in_2 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_stdmatrix< T >::multiplyElements (const Data< T > * matrix_in) [inline], [virtual]
Method multiplying element-by-element of two matrices. One would be the object's contents and the other the parameter's contents. Necessary for implementing Vector to Vector multElements.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::multiplyScalar (const T & scalar) [inline], [virtual]
Multiply scalar method. Multiplies the object's matrix (contents) with a scalar. Necessary for overloading the `*` operator.
Parameters
scalar A scalar factor of template's class.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::read_hb_file (const char * input_file) [inline], [virtual]
Read data in Harwell-Boeing format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Harwell-Boeing format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_stdmatrix< T >::read_mm_file (const char * input_file) [inline], [virtual]
Read data in Matrix Market format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Matrix Market format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
template<typename T> const T& lmx::Type_stdmatrix< T >::readElement (const size_type & mrows, const size_type & ncolumns) const [inline], [virtual]
Read element method. Implements a method for reading data of the dense matrix.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
Returns
Value of the element in the position given by the parameters.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::reset () [inline], [virtual]
Reset method.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_stdmatrix< T >::resize (size_type mrows, size_type ncolumns) [virtual]
Resize method. Changes the size of the contents parameter.
Parameters
mrows New value for rows of dense matrix.
ncolumns New value for columns of dense matrix.
Implements lmx::Data< T >.
Referenced by lmx::Type_stdmatrix< double >::clear(), lmx::Type_stdmatrix< double >::multiply(), lmx::Type_stdmatrix< double >::read_hb_file(), lmx::Type_stdmatrix< double >::read_mm_file(), lmx::Type_stdmatrix< double >::trn(), and lmx::Type_stdmatrix< T >::Type_stdmatrix().
template<typename T> void lmx::Type_stdmatrix< T >::substract (const Data< T > * matrix_in_1) [inline], [virtual]
Substract method. Substracts the the input matrix parameter's elements to the object's contents. Necessary for overloading the `-=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_stdmatrix< T >::trn () [inline], [virtual]
Traspose method. Swaps elements with respect to the diagonal: A(i,j) = A(j,i)
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_stdmatrix< T >::write_hb_file (const char * input_file) [inline], [virtual]
Write data in Harwell-Boeing format method. Opens the file specified and writes the matrix's data in it.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_stdmatrix< T >::writeElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Write element method. Implements a method for writing data on the dense matrix.
Parameters
mrows Row position in dense matrix.
ncolumns Column position in dense matrix.
value Numerical type value.
Implements lmx::Data< T >.
Friends And Related Function Documentation
template<typename T> void copy (const Type_stdmatrix< T > * dense_matrix_in, Type_csc< T > * matrix_in) [friend]
Matrix vector (pre)multiplication, specialized for Type_csc Data_mat (matrix) and Type_stdVector (STL vector) formats. Calculates the product A*b = c using pointers.
Parameters
dense_matrix_in Type_stdMatrix *Matrix B.
matrix_in Type_csc *Matrix A.
template<typename T> friend class DenseMatrix< T > [friend]
The documentation for this class was generated from the following files:
src/LMX/lmx_mat_data_blas.h
src/LMX/lmx_mat_type_stdmatrix.h