Cylinder Class Reference
#include </home/daniel.iglesias/Projects/HeatSurf/src/cylinder.h>
Public Member Functions
Cylinder ()
Cylinder (std::string, double, double, double, int)
~Cylinder ()
void setSections (double)
void computeGeometry ()
void residue (lmx::Vector< double > &, lmx::Vector< double > &)
void jacobian (lmx::Matrix< double > &, lmx::Vector< double > &)
void computeIntersection (Particle *)
void computeNodalPower (Particle *)
void outputTable ()
void outputPowerFile (int)
void outputPowerDensityFile ()
Additional Inherited Members
Detailed Description
Author
Daniel Iglesias daniel.iglesias@ciemat.es
Constructor & Destructor Documentation
Cylinder::Cylinder ()
Cylinder::Cylinder (std::string type_in, double par0_in, double par1_in, double par2_in, int par3_in)
References Geometry::gridWidth.
Cylinder::~Cylinder ()
Member Function Documentation
void Cylinder::computeGeometry () [virtual]
Implements Geometry.
References Geometry::elements, Geometry::grid, Geometry::gridPoints, Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cylinder::computeIntersection (Particle * particle) [virtual]
Implements Geometry.
References Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Particle::getZdiv(), jacobian(), Geometry::paramTrajectories, and residue().
void Cylinder::computeNodalPower (Particle * particle) [virtual]
Implements Geometry.
References Particle::getEnergy(), Particle::getX(), Particle::getXdiv(), Particle::getY(), Particle::getYdiv(), Particle::getZ(), Geometry::length, Geometry::nodes, Geometry::paramTrajectories, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cylinder::jacobian (lmx::Matrix< double > & jac, lmx::Vector< double > & conf)
Referenced by computeIntersection().
void Cylinder::outputPowerDensityFile () [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, Geometry::sectors, and Geometry::z0.
void Cylinder::outputPowerFile (int particles) [virtual]
Implements Geometry.
References Geometry::length, Geometry::nodes, Geometry::sections, and Geometry::sectors.
void Cylinder::outputTable () [virtual]
Implements Geometry.
void Cylinder::residue (lmx::Vector< double > & res, lmx::Vector< double > & conf)
Referenced by computeIntersection().
void Cylinder::setSections (double distance) [virtual]
Implements Geometry.
References Geometry::length, and Geometry::sections.
The documentation for this class was generated from the following files:
src/cylinder.h
src/cylinder.cpp