lmx::DiffProblemFirstSecond< Sys, T > Class Template Reference
Template class DiffProblemFirstSecond. Implementation for weakly coupled First-Second Order ODE system solvers.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_diff_problem_first_second.h>
Public Member Functions
DiffProblemFirstSecond ()
~DiffProblemFirstSecond ()
void setResidue1 (void(Sys::*residue_in)(lmx::Vector< T > &residue1, const lmx::Vector< T > &q1, const lmx::Vector< T > &qdot1, double time))
void setResidue2 (void(Sys::*residue_in)(lmx::Vector< T > &residue2, const lmx::Vector< T > &q22, const lmx::Vector< T > &qdot2, const lmx::Vector< T > &qddot2, double time))
void setJacobian1 (void(Sys::*jacobian_in)(lmx::Matrix< T > &tangent, const lmx::Vector< T > &q, double partial_qdot, double time))
void setJacobian2 (void(Sys::*jacobian_in)(lmx::Matrix< T > &jacobian, const lmx::Vector< T > &q2, const lmx::Vector< T > &qdot2, double partial_qdot2, double partial_qddot2, double time))
void setEvaluation1 (void(Sys::*eval_in)(const lmx::Vector< T > &q1, lmx::Vector< T > &qdot1, double time))
void setEvaluation2 (void(Sys::*eval_in)(const lmx::Vector< T > &q2, const lmx::Vector< T > &qdot2, lmx::Vector< T > &qddot2, double time))
void setIntegrator2 (int type, int opt1=0, int opt2=0)
void setIntegrator2 (const char *type, int opt2=0)
void setIntegrator2 (const char *type, double beta, double gamma, double alpha=0)
void setConvergence (double eps_in)
void setConvergence1 (bool(Sys::*convergence1)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double time))
void setConvergence2 (bool(Sys::*convergence2)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time))
void setSparsePatternJacobian1 (lmx::DenseMatrix< T > &mat_sparse1)
void setSparsePatternJacobian2 (lmx::DenseMatrix< T > &mat_sparse2)
void iterationResidue1 (lmx::Vector< T > &residue, lmx::Vector< T > &q_current)
void iterationJacobian1 (lmx::Matrix< T > &jacobian, lmx::Vector< T > &q_current)
bool iterationConvergence1 (lmx::Vector< T > &q_current)
void iterationResidue2 (lmx::Vector< T > &residue, lmx::Vector< T > &delta_q)
void iterationJacobian2 (lmx::Matrix< T > &jacobian, lmx::Vector< T > &delta_q)
bool iterationConvergence2 (lmx::Vector< T > &delta_q)
void initialize ()
void solve ()
void stepSolve ()
Additional Inherited Members
Detailed Description
template<typename Sys, typename T = double>class lmx::DiffProblemFirstSecond< Sys, T >
Template class DiffProblemFirstSecond. Implementation for weakly coupled First-Second Order ODE system solvers.
This class implements methods for defining and solving initial value problems described by a TotalDiff class' derivided object, and initial conditions in the form $ q(t_o) = q_o $.
Author
Daniel Iglesias.
Constructor & Destructor Documentation
template<typename Sys , typename T = double> lmx::DiffProblemFirstSecond< Sys, T >::DiffProblemFirstSecond () [inline]
Empty constructor.
template<typename Sys , typename T = double> lmx::DiffProblemFirstSecond< Sys, T >::~DiffProblemFirstSecond () [inline]
Destructor.
References lmx::DiffProblemDouble< Sys, T >::p_delta_q1, and lmx::DiffProblemDouble< Sys, T >::p_delta_q2.
Member Function Documentation
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::initialize () [virtual]
Initialize solving function
Implements lmx::DiffProblemDouble< Sys, T >.
References LMX_THROW.
template<typename Sys , typename T > bool lmx::DiffProblemFirstSecond< Sys, T >::iterationConvergence1 (lmx::Vector< T > & q_current)
Function for NLSolver convergence evaluation of 1st order system.
Parameters
q_current Configuration computed by the NLSolver.
template<typename Sys , typename T > bool lmx::DiffProblemFirstSecond< Sys, T >::iterationConvergence2 (lmx::Vector< T > & delta_q)
Function for NLSolver convergence evaluation of 2nd order system.
Parameters
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::iterationJacobian1 (lmx::Matrix< T > & jacobian, lmx::Vector< T > & q_current)
Function for NLSolver jacobian computation for 1st order system.
Parameters
jacobian Tangent matrix.
q_current Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::iterationJacobian2 (lmx::Matrix< T > & jacobian, lmx::Vector< T > & delta_q)
Function for NLSolver jacobian computation for 2nd order system.
Parameters
jacobian Tangent matrix.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::iterationResidue1 (lmx::Vector< T > & residue, lmx::Vector< T > & q_current)
Function for NLSolver residue computation of 1st order system.
Parameters
residue Residue vector.
q_current Configuration computed by the NLSolver.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::iterationResidue2 (lmx::Vector< T > & residue, lmx::Vector< T > & delta_q)
Function for NLSolver residue computation of 2nd order system.
Parameters
residue Residue vector.
delta_q Configuration computed by the NLSolver.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setConvergence (double eps_in) [inline]
Backward resolution of mother function.
Parameters
L2 norm maximum residual.
References lmx::DiffProblemDouble< Sys, T >::setConvergence().
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::setConvergence1 (bool(Sys::*)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, double time) conv_in)
Sets the external function that implements a different convergence criteria from those available in LMX. Must be a Sys member function.
Parameters
conv_in The convergence evaluation function.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::setConvergence2 (bool(Sys::*)(const lmx::Vector< T > &q, const lmx::Vector< T > &qdot, const lmx::Vector< T > &qddot, double time) conv_in)
Sets the external function that implements a different convergence criteria from those available in LMX. Must be a Sys member function.
Parameters
conv_in The convergence evaluation function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setEvaluation1 (void(Sys::*)(const lmx::Vector< T > &q1, lmx::Vector< T > &qdot1, double time) eval_in)
Sets the external (first order configuration) evaluation function. Must be a Sys member function.
Parameters
eval_in The acceleration function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setEvaluation2 (void(Sys::*)(const lmx::Vector< T > &q2, const lmx::Vector< T > &qdot2, lmx::Vector< T > &qddot2, double time) eval_in)
Sets the external (second order configuration) evaluation function. Must be a Sys member function.
Parameters
eval_in The acceleration function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setIntegrator2 (int type, int opt1 = 0, int opt2 = 0) [inline]
Defines the integrator that will be used for second order system configuration advance & updating.
Parameters
type Key of integrator family to use.
opt1 Optional value for some integrators (usually specifies the order).
opt2 Optional value for some integrators.
References lmx::DiffProblemDouble< Sys, T >::setIntegrator2().
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setIntegrator2 (const char * type, int opt2 = 0) [inline]
Defines the integrator that will be used for configuration advance & updating.
Parameters
type Key of integrator family to use.
opt2 Optional value for some integrators.
References lmx::DiffProblemDouble< Sys, T >::setIntegrator2().
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::setIntegrator2 (const char * type, double beta_in, double gamma_in, double alpha_in = 0)
Defines the integrator that will be used for configuration advance & updating (Alpha version).
Parameters
type Key of integrator family to use.
alpha_in HHT's alpha. Defines the integrator that will be used for configuration advance & updating (Newmark and Alpha version).
type Key of integrator family to use.
beta_in Newmark's beta.
gamma_in Newmark's gamma.
alpha_in HHT's alpha.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::setJacobian1 (void(Sys::*)(lmx::Matrix< T > &tangent, const lmx::Vector< T > &q, double partial_qdot, double time) jacobian_in)
Sets the external function for tangent to q. Must be a Sys member function. :::change documentation:::
Parameters
jacobian_in Tangent function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setJacobian2 (void(Sys::*)(lmx::Matrix< T > &jacobian, const lmx::Vector< T > &q2, const lmx::Vector< T > &qdot2, double partial_qdot2, double partial_qddot2, double time) jacobian_in)
Sets the external function for tangent to q. Must be a Sys member function. ::: change documentation :::
Parameters
jacobian_in Tangent function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setResidue1 (void(Sys::*)(lmx::Vector< T > &residue1, const lmx::Vector< T > &q1, const lmx::Vector< T > &qdot1, double time) residue_in)
Sets the external function for residue evaluation. Must be a Sys member function.
Parameters
residue_in Residue function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setResidue2 (void(Sys::*)(lmx::Vector< T > &residue2, const lmx::Vector< T > &q22, const lmx::Vector< T > &qdot2, const lmx::Vector< T > &qddot2, double time) residue_in)
Sets the external function for residue evaluation. Must be a Sys member function.
Parameters
residue_in Residue function.
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setSparsePatternJacobian1 (lmx::DenseMatrix< T > & mat_sparse1) [inline]
References lmx::DenseMatrix< T >::writeSparsePattern().
template<typename Sys , typename T = double> void lmx::DiffProblemFirstSecond< Sys, T >::setSparsePatternJacobian2 (lmx::DenseMatrix< T > & mat_sparse2) [inline]
References lmx::DenseMatrix< T >::writeSparsePattern().
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::solve () [virtual]
Solve main function
Implements lmx::DiffProblemDouble< Sys, T >.
template<typename Sys , typename T > void lmx::DiffProblemFirstSecond< Sys, T >::stepSolve () [virtual]
Solve only one step
Implements lmx::DiffProblemDouble< Sys, T >.
References LMX_THROW.
The documentation for this class was generated from the following file:
src/LMX/lmx_diff_problem_first_second.h