lmx::Type_csc< T > Class Template Reference
Compressed Storaged by Columns matrix.
#include </home/daniel.iglesias/Projects/HeatSurf/src/LMX/lmx_mat_data_blas.h>
Public Member Functions
Type_csc ()
Empty constructor.
Type_csc (size_type rows, size_type columns)
~Type_csc ()
Destructor.
void resize (size_type, size_type)
const T & readElement (const size_type &mrows, const size_type &ncolumns) const
void writeElement (T value, const size_type &mrows, const size_type &ncolumns)
void addElement (T value, const size_type &mrows, const size_type &ncolumns)
T * create_element (size_type, size_type)
size_type getRows () const
size_type getCols () const
void equals (const Data< T > *matrix_in)
void add (const Data< T > *matrix_in_1)
void substract (const Data< T > *matrix_in_1)
void multiply (const Data< T > *matrix_in_1, const Data< T > *matrix_in_2)
void multiplyScalar (const T &)
void multiplyElements (const Data< T > *matrix_in)
void trn ()
void cleanBelow (const double factor)
void clear ()
void reset ()
void read_mm_file (const char *input_file)
void read_hb_file (const char *input_file)
void write_hb_file (const char *input_file)
void print ()
bool exists (size_type, size_type)
void setSparsePattern (Vector< size_type > &, Vector< size_type > &)
void setSparsePattern (std::vector< size_type > &, std::vector< size_type > &)
void initSLU ()
void factorize ()
void subsSolve (Vector< T > &rhs)
Public Attributes
std::vector< T > aa
std::vector< size_type > ia
std::vector< size_type > ja
size_type Nnze
size_type Nrow
size_type Ncol
Friends
void mat_vec_mult (const Type_csc< T > *, const Type_stdVector< T > *, Type_stdVector< T > *)
Detailed Description
template<typename T>class lmx::Type_csc< T >
Compressed Storaged by Columns matrix.
Author
Roberto Ortega
Constructor & Destructor Documentation
template<typename T > lmx::Type_csc< T >::Type_csc ()
Empty constructor.
template<typename T > lmx::Type_csc< T >::Type_csc (size_type rows, size_type columns)
Standard constructor. Creates a new object with parameter contents resized to (rows, columns) dimension.
Parameters
rows Rows of H-B matrix.
columns Columns of H-B matrix.
References lmx::Type_csc< T >::ja, lmx::Type_csc< T >::Ncol, lmx::Type_csc< T >::Nnze, lmx::Type_csc< T >::Nrow, and lmx::Type_csc< T >::resize().
template<typename T > lmx::Type_csc< T >::~Type_csc ()
Destructor.
Member Function Documentation
template<typename T > void lmx::Type_csc< T >::add (const Data< T > * matrix_in_1) [virtual]
Add method. Adds the the input matrix parameter's elements to the object's contents. Necessary for overloading the `+=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data_mat.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T > void lmx::Type_csc< T >::addElement (T value, const size_type & mrows, const size_type & ncolumns) [inline], [virtual]
Add element method. Implements a method for adding data on the Harwell-Boeing matrix. Copy-pasted from writeElement.
Parameters
mrows Row position in Harwell-Boeing matrix.
ncolumns Column position in Harwell-Boeing matrix.
value Numerical type value.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_csc< T >::cleanBelow (const double factor) [virtual]
Clean below method. Makes equal to zero every element below given factor.
Parameters
factor Reference value for cleaning.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_csc< T >::clear () [virtual]
Clear method. Wipes all data, clearing column, row and data vectors. < Matrix data contents.
< Row indexer.
< Column indexer.
< Number of non-zero values.
Implements lmx::Data< T >.
template<typename T > T * lmx::Type_csc< T >::create_element (size_type mrows, size_type ncolumns)
Create element method. Implements a method for creating a new data position in matrix.
Parameters
mrows Row position in Harwell-Boeing matrix.
ncolumns Column position in Harwell-Boeing matrix.
Returns
A pointer to the element in the position given by the parameters.
template<typename T > void lmx::Type_csc< T >::equals (const Data< T > * matrix_in) [virtual]
Copy method. Equals the data in the object's contents to those given by the input matrix parameter.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data_mat.
Implements lmx::Data< T >.
template<typename T > bool lmx::Type_csc< T >::exists (size_type mrows, size_type ncolumns) [virtual]
Returns TRUE or FALSE depending of element existance.
Parameters
mrows Row index.
ncolumns Column index.
Returns
TRUE if the element exists in internal storage structure.
Implements lmx::Data_mat< T >.
template<typename T> void lmx::Type_csc< T >::factorize (void) [inline], [virtual]
Implements lmx::Data_mat< T >.
template<typename T > size_type lmx::Type_csc< T >::getCols () const [inline], [virtual]
Method for knowing the number of data columns.
Returns
Number of columns.
Implements lmx::Data< T >.
Referenced by lmx::copy(), and lmx::mat_vec_mult().
template<typename T > size_type lmx::Type_csc< T >::getRows () const [inline], [virtual]
Method for knowing the number of data rows.
Returns
Number of rows.
Implements lmx::Data< T >.
Referenced by lmx::copy(), and lmx::mat_vec_mult().
template<typename T> void lmx::Type_csc< T >::initSLU () [inline]
template<typename T > void lmx::Type_csc< T >::multiply (const Data< T > * matrix_in_1, const Data< T > * matrix_in_2) [virtual]
Multiply method. Multiplies the input matrices and saves the result into the object's contents. Necessary for overloading the `*` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data_mat.
matrix_in_2 pointer to an object that belongs to a class derived from Data_mat.
Implements lmx::Data_mat< T >.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), and lmx::Data< T >::readElement().
template<typename T > void lmx::Type_csc< T >::multiplyElements (const Data< T > * matrix_in) [virtual]
Method multiplying element-by-element of two matrices. One would be the object's contents and the other the parameter's contents.
Necessary for implementing Vector to Vector multElements.
Parameters
matrix_in pointer to an object that belongs to a class derived from Data.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T > void lmx::Type_csc< T >::multiplyScalar (const T & scalar) [virtual]
Multiply scalar method. Multiplies the object's matrix (contents) with a scalar. Necessary for overloading the `*` operator.
Parameters
scalar A scalar factor of template's class.
Implements lmx::Data< T >.
template<typename T> void lmx::Type_csc< T >::print () [inline]
Function for testing purposes.
References lmx::Type_csc< T >::aa, lmx::Type_csc< T >::ia, lmx::Type_csc< T >::ja, and lmx::Type_csc< T >::Nnze.
template<typename T > void lmx::Type_csc< T >::read_hb_file (const char * input_file) [virtual]
Read data in Harwell-Boeing format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Harwell-Boeing format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
template<typename T > void lmx::Type_csc< T >::read_mm_file (const char * input_file) [virtual]
Read data in Matrix Market format method. Opens the file specified and reads the matrix's data in it, suposing it's stored in Matrix Market format.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
References lmx::copy(), and LMX_THROW.
template<typename T > const T & lmx::Type_csc< T >::readElement (const size_type & mrows, const size_type & ncolumns) const [virtual]
Read element method. Implements a method for reading data of the Harwell-Boeing matrix.
Parameters
mrows Row position in Harwell-Boeing matrix.
ncolumns Column position in Harwell-Boeing matrix.
Returns
Value of the element in the position given by the parameters.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_csc< T >::reset () [virtual]
Reset method.
Implements lmx::Data< T >.
template<typename T > void lmx::Type_csc< T >::resize (size_type mrows, size_type ncolumns) [virtual]
Resize method. Changes the size of the sparse matrix.
Parameters
mrows New value for rows of matrix.
ncolumns New value for columns of matrix.
Implements lmx::Data< T >.
Referenced by lmx::Type_csc< T >::Type_csc().
template<typename T > void lmx::Type_csc< T >::setSparsePattern (Vector< size_type > & row_index, Vector< size_type > & col_index) [virtual]
Prepares the sparse structure of a CSC matrix.
Parameters
row_index CSC row indices.
col_index CSC columns indices.
Reimplemented from lmx::Data_mat< T >.
References lmx::Vector< T >::size().
template<typename T > void lmx::Type_csc< T >::setSparsePattern (std::vector< size_type > & row_index, std::vector< size_type > & col_index) [virtual]
Prepares the sparse structure of a CSC matrix.
Parameters
row_index CSC row indices.
col_index CSC columns indices.
Reimplemented from lmx::Data_mat< T >.
template<typename T> void lmx::Type_csc< T >::subsSolve (Vector< T > & rhs) [inline], [virtual]
Reimplemented from lmx::Data_mat< T >.
template<typename T > void lmx::Type_csc< T >::substract (const Data< T > * matrix_in_1) [virtual]
Substract method. Substracts the the input matrix parameter's elements to the object's contents. Necessary for overloading the `-=` operator.
Parameters
matrix_in_1 pointer to an object that belongs to a class derived from Data_mat.
Implements lmx::Data< T >.
References lmx::Data< T >::readElement().
template<typename T > void lmx::Type_csc< T >::trn () [virtual]
Traspose method. Swaps elements with respect to the diagonal: A(i,j) = A(j,i)
Implements lmx::Data_mat< T >.
template<typename T > void lmx::Type_csc< T >::write_hb_file (const char * input_file) [virtual]
Write data in Harwell-Boeing format method. Opens the file specified and writes the matrix's data in it.
Parameters
input_file Name of the file to be read.
Implements lmx::Data_mat< T >.
References LMX_THROW.
template<typename T > void lmx::Type_csc< T >::writeElement (T value, const size_type & mrows, const size_type & ncolumns) [virtual]
Write element method. Implements a method for writing data on the Harwell-Boeing matrix.
Parameters
mrows Row position in Harwell-Boeing matrix.
ncolumns Column position in Harwell-Boeing matrix.
value Numerical type value.
Implements lmx::Data< T >.
Friends And Related Function Documentation
template<typename T> void mat_vec_mult (const Type_csc< T > * matrix_in, const Type_stdVector< T > * vector_in, Type_stdVector< T > * vector_out) [friend]
Matrix vector (pre)multiplication, specialized for Type_csc Data_mat (matrix) and Type_stdVector (STL vector) formats. Calculates the product A*b = c using pointers.
Parameters
matrix_in Type_csc *Matrix A.
vector_in Type_stdVector *Vector b.
vector_out Type_stdVector *Vector c = A*b.
Member Data Documentation
template<typename T> std::vector<T> lmx::Type_csc< T >::aa
Matrix data contents.
Referenced by lmx::copy(), lmx::mat_vec_mult(), and lmx::Type_csc< T >::print().
template<typename T> std::vector<size_type> lmx::Type_csc< T >::ia
Row indexer.
Referenced by lmx::copy(), lmx::mat_vec_mult(), and lmx::Type_csc< T >::print().
template<typename T> std::vector<size_type> lmx::Type_csc< T >::ja
Column indexer.
Referenced by lmx::copy(), lmx::mat_vec_mult(), lmx::Type_csc< T >::print(), and lmx::Type_csc< T >::Type_csc().
template<typename T> size_type lmx::Type_csc< T >::Ncol
Number of columns.
Referenced by lmx::copy(), and lmx::Type_csc< T >::Type_csc().
template<typename T> size_type lmx::Type_csc< T >::Nnze
Number of non-zero values.
Referenced by lmx::copy(), lmx::Type_csc< T >::print(), and lmx::Type_csc< T >::Type_csc().
template<typename T> size_type lmx::Type_csc< T >::Nrow
Number of rows.
Referenced by lmx::copy(), and lmx::Type_csc< T >::Type_csc().
The documentation for this class was generated from the following files:
src/LMX/lmx_mat_data_blas.h
src/LMX/lmx_mat_type_csc.h