src/LMX/cofe_fmc.h File Reference
#include `cofe_TensorRank1.h`
*
#include `cofe_TensorRank2.h`
*
#include `cofe_TensorRank2Sym.h`
*
#include <limits>
*
Functions
template<int DIM>
cofe::TensorRank1< DIM > operator+ (const typename cofe::TensorRank1< DIM > &v1, const typename cofe::TensorRank1< DIM > &v2)
template<int DIM>
cofe::TensorRank1< DIM > operator- (const cofe::TensorRank1< DIM > &v1, const cofe::TensorRank1< DIM > &v2)
template<int DIM>
cofe::TensorRank1< DIM > operator* (const double a, const cofe::TensorRank1< DIM > &v)
template<int DIM>
cofe::TensorRank1< DIM > operator* (const cofe::TensorRank2< DIM > &T, const cofe::TensorRank1< DIM > &v)
template<int DIM>
cofe::TensorRank2< DIM > operator+ (const cofe::TensorRank2< DIM > &T1, const cofe::TensorRank2< DIM > &T2)
template<int DIM>
cofe::TensorRank2< DIM > operator- (const cofe::TensorRank2< DIM > &T1, const cofe::TensorRank2< DIM > &T2)
template<int DIM, class C >
cofe::TensorRank2< DIM > operator* (const C a, const cofe::TensorRank2< DIM > &T)
template<int DIM, class C >
cofe::TensorRank2< DIM > operator* (const cofe::TensorRank2< DIM > &T, const C a)
template<int DIM, typename T >
cofe::TensorRank2< DIM, T > operator* (const cofe::TensorRank2< DIM, T > &T1, const cofe::TensorRank2< DIM, T > &T2)
template<int DIM>
cofe::TensorRank2< DIM > transposeOf (const cofe::TensorRank2< DIM > &T)
template<int DIM>
cofe::TensorRank2< DIM > inverseOf (const cofe::TensorRank2< DIM > &T)
template<int DIM>
cofe::TensorRank2Sym< DIM > operator+ (const cofe::TensorRank2Sym< DIM > &T1, const cofe::TensorRank2Sym< DIM > &T2)
template<int DIM>
cofe::TensorRank2Sym< DIM > operator- (const cofe::TensorRank2Sym< DIM > &T1, const cofe::TensorRank2Sym< DIM > &T2)
template<int DIM>
cofe::TensorRank2Sym< DIM > operator* (const double a, const cofe::TensorRank2Sym< DIM > &T)
template<int DIM>
cofe::TensorRank2Sym< DIM > transposeOf (const cofe::TensorRank2Sym< DIM > &T)
Function Documentation
template<int DIM> cofe::TensorRank2<DIM> inverseOf (const cofe::TensorRank2< DIM > & T) [inline]
References cofe::TensorRank2< Dim, T >::determinant(), and cofe::CofeUtils::error().
template<int DIM> cofe::TensorRank1<DIM> operator* (const double a, const cofe::TensorRank1< DIM > & v) [inline]
template<int DIM> cofe::TensorRank1<DIM> operator* (const cofe::TensorRank2< DIM > & T, const cofe::TensorRank1< DIM > & v) [inline]
References cofe::TensorRank1< Dim, T >::beProductOf().
template<int DIM, class C > cofe::TensorRank2<DIM> operator* (const C a, const cofe::TensorRank2< DIM > & T) [inline]
template<int DIM, class C > cofe::TensorRank2<DIM> operator* (const cofe::TensorRank2< DIM > & T, const C a) [inline]
template<int DIM, typename T > cofe::TensorRank2<DIM, T> operator* (const cofe::TensorRank2< DIM, T > & T1, const cofe::TensorRank2< DIM, T > & T2) [inline]
References cofe::TensorRank2< Dim, T >::beProductOf().
template<int DIM> cofe::TensorRank2Sym<DIM> operator* (const double a, const cofe::TensorRank2Sym< DIM > & T) [inline]
template<int DIM> cofe::TensorRank1<DIM> operator+ (const typename cofe::TensorRank1< DIM > & v1, const typename cofe::TensorRank1< DIM > & v2) [inline]
template<int DIM> cofe::TensorRank2<DIM> operator+ (const cofe::TensorRank2< DIM > & T1, const cofe::TensorRank2< DIM > & T2) [inline]
template<int DIM> cofe::TensorRank2Sym<DIM> operator+ (const cofe::TensorRank2Sym< DIM > & T1, const cofe::TensorRank2Sym< DIM > & T2) [inline]
template<int DIM> cofe::TensorRank1<DIM> operator- (const cofe::TensorRank1< DIM > & v1, const cofe::TensorRank1< DIM > & v2) [inline]
template<int DIM> cofe::TensorRank2<DIM> operator- (const cofe::TensorRank2< DIM > & T1, const cofe::TensorRank2< DIM > & T2) [inline]
template<int DIM> cofe::TensorRank2Sym<DIM> operator- (const cofe::TensorRank2Sym< DIM > & T1, const cofe::TensorRank2Sym< DIM > & T2) [inline]
template<int DIM> cofe::TensorRank2<DIM> transposeOf (const cofe::TensorRank2< DIM > & T) [inline]
References cofe::TensorRank2< Dim, T >::beTransposeOf().
template<int DIM> cofe::TensorRank2Sym<DIM> transposeOf (const cofe::TensorRank2Sym< DIM > & T) [inline]