src/heatsurf.cpp File Reference
#include <unistd.h>
*
#include <iostream>
*
#include <cstdlib>
*
#include <LMX/lmx_base_stopwatch.h>
*
#include `simulation.h`
*
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References Simulation::compute(), Simulation::output(), and Simulation::read().