src/LMX/lmx_mat_matrix.h File Reference
This file contains both the declaration and implementation for Matrix class member and friend functions.
#include <cmath>
*
#include `lmx_except.h`
*
#include `lmx_mat_type_stdmatrix.h`
*
#include `lmx_mat_type_csc.h`
*
Classes
class Vector< T >
class LinearSystem< T >
class Matrix< T >
Template class Matrix.
Namespaces
lmx
Linked MatriX methods library uses lmx namespace.
Functions
int setMatrixType (int)
int getMatrixType ()
template<typename C >
void latexPrint (std::ofstream &os, char *mat_name, Matrix< C > &mat, int prec)
template<typename C >
void lmx::latexPrint (std::ofstream &os, char *mat_name, Matrix< C > &mat, int prec)
template<typename T >
Matrix< T > lmx::operator- (const Matrix< T > &B)
template<typename T >
Matrix< T > lmx::operator* (const T &scalar, const Matrix< T > &B)
template<class T >
std::ostream & lmx::operator<< (std::ostream &os, const Matrix< T > &mat)
template<class T >
std::ostream & lmx::operator<< (std::ostream &os, const Matrix< cofe::TensorRank2< 3, T > > &mat)
Detailed Description
This file contains both the declaration and implementation for Matrix class member and friend functions.
Author
Daniel Iglesias
Function Documentation
int getMatrixType () [inline]
Function reads the type of Matrix container that is used.
References lmx::setMatrixType().
Referenced by lmx::LinearSystem< T >::factorize(), Matrix< T >::Matrix(), lmx::Vector< T >::mult(), Matrix< T >::operator=(), lmx::LinearSystem< T >::setA(), lmx::LinearSystem< T >::setb(), lmx::solveLinear(), lmx::LinearSystem< T >::solveYourself(), and lmx::LinearSystem< T >::subsSolve().
template<typename C > void latexPrint (std::ofstream & os, char * mat_name, Matrix< C > & mat, int prec)
int setMatrixType (int type) [inline]
Function that changes the type of matrix container that will be used.
References LMX_THROW.
Referenced by getMatrixType().