lmx Namespace Reference
Linked MatriX methods library uses lmx namespace.
Classes
struct HarwellBoeing_IO
class Stopwatch
Class Stopwatch.
class ExactStopwatch
Class ExactStopwatch.
class Configuration
Template class Configuration.
class IntegratorAB
Template class IntegratorAB. Adams-Bashford integrator implementation for ODE systems.
class IntegratorAM
Template class IntegratorAM. Adams-Moulton integrator implementation for ODE systems.
class IntegratorBase
Template abstract class IntegratorBase.
class IntegratorBaseImplicit
Template abstract class IntegratorBaseImplicit.
class IntegratorBDF
Template class IntegratorBDF. Gear's BDF integrator implementation for ODE systems.
class IntegratorCentralDifference
Template class IntegratorCentralDifference. Central difference integrator implementation for ODE systems.
class IntegratorNEWMARK
Template class IntegratorNEWMARK. Gear's BDF integrator implementation for ODE systems.
class DiffProblem
Template class DiffProblem. Implementation for ODE system solvers.
class DiffProblemDouble
Template class DiffProblemDouble. Implementation for ODE system solvers.
class DiffProblemFirst
Template class DiffProblemFirst. Implementation for First Order ODE system solvers.
class DiffProblemFirstSecond
Template class DiffProblemFirstSecond. Implementation for weakly coupled First-Second Order ODE system solvers.
class DiffProblemSecond
Template class DiffProblemSecond. Implementation for Fist Order ODE system solvers.
class dimension_error
Manages matrices and vectors dimension errors.
class file_not_found_error
Manages read/write methods' errors when checking file names.
class internal_error
Manages errors that occur inside LMX methods and functions.
class failure_error
Manages other errors not classified above.
class to_be_done_error
Manages errors in methods witch implementation is not finished.
struct exception_callback
Callback handler for lmx exceptions.
struct exception_callback_debug
crashing callback for debug mode.
struct warning_level
Manages importance level in warnings.
class Cg
Template class Cg. This class implements the conjugate gradient iterative linear solver, with and without preconditioner. It uses LMX matrix and vector facilities so any kind of linked object can be used.
class Gesv
Template class for lapack ?gesv routine.
class LU
Template class LU for solving linear systems.
class Superlu
Template class LinearSystem. Linear systems implementation: `A*x = b` .
class LinearSystem
Template class LinearSystem. Linear systems implementation: `A*x = b` .
class Data
Template class Data. Mother class for Data_mat & Data_vec.
class Data_mat
Template class Data_mat. Container for Matrix and Vector data.
class Data_vec
Template class Data_vec. Container for Vector data.
class Type_stdmatrix
Template class Type_stdmatrix.
class Type_csc
Compressed Storaged by Columns matrix.
class Type_stdVector
Template class Type_stdVector.
class Vector
Template class Vector.
class Matrix
class DenseMatrix
Template class DenseMatrix.
class Elem_ref
Template class Elem_ref.
class Type_gmm
Template class Type_gmm.
class Type_gmm_sparse
Template class Type_gmm_sparse.
class Type_gmmVector_sparse
Template class Type_gmmVector_sparse.
class NLSolver
Template class NLSolver. Non-linear systems implementation: `R(q) = 0` .
class NLSolverDouble
Template class NLSolverDouble. Non-linear systems implementation: `R(q) = 0` .
Functions
int setMatrixType (int type)
int setVectorType (int type)
int setLinSolverType (int type)
int getMatrixType ()
int getVectorType ()
int getLinSolverType ()
void set_exception_callback (exception_callback *e)
void set_warning_level (int l)
template<typename T >
void solveLinear (Matrix< T > &A, Vector< T > &x, Vector< T > &b)
Automatized driver for solving a linear system.
template<typename T >
void mat_mat_add (const Data_mat< T > *A, const Data_mat< T > *B, Data_mat< T > *C)
template<typename T >
void mat_mat_subs (const Data_mat< T > *A, const Data_mat< T > *B, Data_mat< T > *C)
template<typename T >
void mat_mat_mult (const Data_mat< T > *A, const Data_mat< T > *B, Data_mat< T > *C)
template<typename T >
void mat_mat_multElements (const Data_mat< T > *A, Data_mat< T > *C)
template<typename T >
void mat_mat_multElements (const Data_mat< T > *A, const Data_mat< T > *B, Data_mat< T > *C)
template<typename T >
void mat_vec_mult (const Type_csc< T > *matrix_in, const Type_stdVector< T > *vector_in, Type_stdVector< T > *vector_out)
template<typename T >
void copy (const Type_stdmatrix< T > *dense_matrix_in, Type_csc< T > *matrix_in)
template<typename T >
DenseMatrix< T > operator- (const DenseMatrix< T > &B)
template<typename C >
void latexPrint (std::ofstream &os, char *mat_name, Matrix< C > &mat, int prec)
template<typename T >
Matrix< T > operator- (const Matrix< T > &B)
template<typename T >
Matrix< T > operator* (const T &scalar, const Matrix< T > &B)
template<class T >
std::ostream & operator<< (std::ostream &os, const Matrix< T > &mat)
template<class T >
std::ostream & operator<< (std::ostream &os, const Matrix< cofe::TensorRank2< 3, T > > &mat)
template<typename T >
Vector< T > operator* (const Matrix< T > &A, const Vector< T > &b)
template<typename T >
Vector< T > operator* (const DenseMatrix< T > &A, const Vector< T > &b)
template<typename T >
Vector< T > operator* (const T &a, const Vector< T > &B)
template<typename T >
std::ostream & operator<< (std::ostream &os, const Vector< T > &vec)
Variables
constexpr int nl_solver_type = 0
Detailed Description
Linked MatriX methods library uses lmx namespace. {}
This is the namespace that contains LMX-lite.
Function Documentation
template<typename T > void lmx::copy (const Type_stdmatrix< T > * dense_matrix_in, Type_csc< T > * matrix_in)
Matrix vector (pre)multiplication, specialized for Type_csc Data_mat (matrix) and Type_stdVector (STL vector) formats. Calculates the product A*b = c using pointers.
Parameters
dense_matrix_in Type_stdMatrix *Matrix B.
matrix_in Type_csc *Matrix A.
References lmx::Type_csc< T >::aa, lmx::Type_csc< T >::getCols(), lmx::Type_csc< T >::getRows(), lmx::Type_csc< T >::ia, lmx::Type_csc< T >::ja, lmx::Type_csc< T >::Ncol, lmx::Type_csc< T >::Nnze, and lmx::Type_csc< T >::Nrow.
Referenced by lmx::Type_gmm< T >::read_hb_file(), lmx::Type_gmm_sparse< T >::read_hb_file(), lmx::Type_csc< T >::read_mm_file(), lmx::Type_gmm< T >::read_mm_file(), lmx::Type_gmm_sparse< T >::read_mm_file(), lmx::Type_stdmatrix< double >::read_mm_file(), lmx::Type_gmm< T >::trn(), lmx::Type_gmm_sparse< T >::trn(), lmx::Type_gmm< T >::write_hb_file(), lmx::Type_gmm_sparse< T >::write_hb_file(), and lmx::Type_stdmatrix< double >::write_hb_file().
int lmx::getLinSolverType () [inline]
Function reads the type of LinearSystem that is used.
References setLinSolverType().
Referenced by solveLinear(), and lmx::LinearSystem< T >::solveYourself().
int lmx::getMatrixType () [inline]
Function reads the type of Matrix container that is used.
References setMatrixType().
Referenced by lmx::LinearSystem< T >::factorize(), Matrix< T >::Matrix(), lmx::Vector< T >::mult(), Matrix< T >::operator=(), lmx::LinearSystem< T >::setA(), lmx::LinearSystem< T >::setb(), solveLinear(), lmx::LinearSystem< T >::solveYourself(), and lmx::LinearSystem< T >::subsSolve().
int lmx::getVectorType () [inline]
Function reads the type of Vector container that is used.
References setVectorType().
Referenced by lmx::Vector< T >::mult(), lmx::LinearSystem< T >::solveYourself(), and lmx::Vector< T >::Vector().
template<typename C > void lmx::latexPrint (std::ofstream & os, char * mat_name, Matrix< C > & mat, int prec)
template<typename T > void lmx::mat_mat_add (const Data_mat< T > * A, const Data_mat< T > * B, Data_mat< T > * C)
Matrix and DenseMatrix compatible addition. Calculates the operation A+B = C.
Parameters
A LHS Data_mat<T>.
B RHS Data_mat<T>.
C Result Data_mat<T>, C=A+B.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), lmx::Data< T >::readElement(), and lmx::Data< T >::writeElement().
template<typename T > void lmx::mat_mat_mult (const Data_mat< T > * A, const Data_mat< T > * B, Data_mat< T > * C)
Matrix and DenseMatrix compatible multiplication. Calculates the product A*B = C.
Parameters
A LHS Data_mat<T>.
B RHS Data_mat<T>.
C Result Data_mat<T>, C=A*B.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), LMX_THROW, lmx::Data< T >::readElement(), lmx::Data< T >::resize(), and lmx::Data< T >::writeElement().
Referenced by lmx::DenseMatrix< T >::mult(), and Matrix< T >::mult().
template<typename T > void lmx::mat_mat_multElements (const Data_mat< T > * A, Data_mat< T > * C)
Matrix and DenseMatrix compatible element-by-element multiplication with one operand. Calculates the operation C(i,j) *= A(i,j).
Parameters
A Data_mat<T>.
C Result Data_mat<T>.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), lmx::Data< T >::readElement(), and lmx::Data< T >::writeElement().
Referenced by lmx::DenseMatrix< T >::multElements().
template<typename T > void lmx::mat_mat_multElements (const Data_mat< T > * A, const Data_mat< T > * B, Data_mat< T > * C)
Matrix and DenseMatrix compatible element-by-element multiplication. Calculates the operation A(i,j) * B(i,j) = C(i,j).
Parameters
A LHS Data_mat<T>.
B RHS Data_mat<T>.
C Result Data_mat<T>.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), lmx::Data< T >::readElement(), and lmx::Data< T >::writeElement().
template<typename T > void lmx::mat_mat_subs (const Data_mat< T > * A, const Data_mat< T > * B, Data_mat< T > * C)
Matrix and DenseMatrix compatible substraction. Calculates the operation A-B = C.
Parameters
A LHS Data_mat<T>.
B RHS Data_mat<T>.
C Result Data_mat<T>, C=A-B.
References lmx::Data< T >::getCols(), lmx::Data< T >::getRows(), lmx::Data< T >::readElement(), and lmx::Data< T >::writeElement().
template<typename T > void lmx::mat_vec_mult (const Type_csc< T > * matrix_in, const Type_stdVector< T > * vector_in, Type_stdVector< T > * vector_out)
Matrix vector (pre)multiplication, specialized for Type_csc Data_mat (matrix) and Type_stdVector (STL vector) formats. Calculates the product A*b = c using pointers.
Parameters
matrix_in Type_csc *Matrix A.
vector_in Type_stdVector *Vector b.
vector_out Type_stdVector *Vector c = A*b.
References lmx::Type_csc< T >::aa, lmx::Type_csc< T >::getCols(), lmx::Type_csc< T >::getRows(), lmx::Type_csc< T >::ia, and lmx::Type_csc< T >::ja.
template<typename T > Vector<T> lmx::operator* (const Matrix< T > & A, const Vector< T > & b)
Operator for multiplying Matrix and Vector objects. Performs typical vector operation: A * b = c, where b & c are vectors and A is a Matrix.
Parameters
A Matrix reference for first LHS term.
b Vector reference for second LHS term.
Returns
A new Vector (c = A*b).
References LMX_THROW, lmx::Vector< T >::mult(), and lmx::Vector< T >::size().
template<typename T > Vector<T> lmx::operator* (const DenseMatrix< T > & A, const Vector< T > & b)
Operator for multiplying DenseMatrix and Vector objects. Performs typical vector operation: A * b = c, where b & c are vectors and A is a DenseMatrix.
Parameters
A DenseMatrix reference for first LHS term.
b Vector reference for second LHS term.
Returns
A new Vector (c = A*b).
References LMX_THROW, lmx::Vector< T >::mult(), and lmx::Vector< T >::size().
template<typename T > Vector<T> lmx::operator* (const T & a, const Vector< T > & B)
Overload operator for multiplying a scalar and a Vector object.
Parameters
a scalar reference.
B Vector reference for second LHS term.
Returns
A new Vector (mult = a*b).
template<typename T > Matrix<T> lmx::operator* (const T & scalar, const Matrix< T > & B)
Overload operator for multiplying a scalar and a Matrix object. Scheme of function: mult=A*B, return B;
template<typename T > DenseMatrix<T> lmx::operator- (const DenseMatrix< T > & B)
Overload operator for negation. Scheme of function: res=1*-A, return res;
template<typename T > Matrix<T> lmx::operator- (const Matrix< T > & B)
Overload operator for negation. Scheme of function: res=1*-A, return res;
template<typename T > std::ostream& lmx::operator<< (std::ostream & os, const Vector< T > & vec)
Overloaded operator that prints a Vector object into the output stream selected.
Parameters
vec Vector reference to the object that is going to be printed.
os An output std stream.
Returns
(os) The stream that was passed as a parameter.
References lmx::Vector< T >::size().
template<class T > std::ostream& lmx::operator<< (std::ostream & os, const Matrix< T > & mat)
Overloaded operator that prints a Matrix<T> object into the output stream selected.
Parameters
mat Matrix<T> reference to the object that is going to be printed.
os An output std stream.
Returns
(os) The stream that was passed as a parameter.
template<class T > std::ostream& lmx::operator<< (std::ostream & os, const Matrix< cofe::TensorRank2< 3, T > > & mat)
Overloaded operator that prints a Matrix<T> object into the output stream selected. Specialized for cofe::TensorRank2<3> order 2 Tensors.
Parameters
mat Matrix<T> reference to the object that is going to be printed.
os An output std stream.
Returns
(os) The stream that was passed as a parameter.
void lmx::set_exception_callback (exception_callback * e) [inline]
User's function for changing the default exception callback
Parameters
e Pointer to the new exception callback.
void lmx::set_warning_level (int l) [inline]
user function for changing the level warning.
References lmx::warning_level::level().
int lmx::setLinSolverType (int type) [inline]
Function that changes the type of linear solver that will be used.
Referenced by getLinSolverType(), and solveLinear().
int lmx::setMatrixType (int type) [inline]
Function that changes the type of matrix container that will be used.
References LMX_THROW.
Referenced by getMatrixType().
int lmx::setVectorType (int type) [inline]
Function that changes the type of vector container that will be used.
References LMX_THROW.
Referenced by getVectorType().
template<typename T > void lmx::solveLinear (Matrix< T > & A, Vector< T > & x, Vector< T > & b)
Automatized driver for solving a linear system.
Tries to guess the solver that better fits the system. It's use is intended for fast developing of non-optimized applications. For better performance and control of application, use the LinearSystem class.
Parameters
A LHS Matrix.
x LHS Vector of unknowns.
b RHS Vector.
References getLinSolverType(), getMatrixType(), setLinSolverType(), and lmx::LinearSystem< T >::solveYourself().
Variable Documentation
constexpr int lmx::nl_solver_type = 0
This variable switches between different types of non-linear solvers.
Referenced by lmx::NLSolver< Sys, T >::solve(), and lmx::NLSolverDouble< Sys, T >::solve().