cofe Namespace Reference
Continuum Oriented Finite Elements.
Classes
class CofeUtils
class TensorRank2
class TensorRank1
class AbstractTensorRank4SS
class TensorRank2Sym
Functions
template<class T >
double norm (const T &a)
template<int N, class T >
void gausselim (T a[N][N], T b[N])
template<int N, class T >
void jacobi (T a[N][N], T d[N], T v[N][N], int &nrot)
template<int N, class T >
void rot (T a[N][N], T s, T tau, int i, int j, int k, int l)
template<int Dim, class T >
std::ostream & operator<< (std::ostream &os, const cofe::TensorRank1< Dim, T > &a)
template<int Dim, class T >
std::ostream & operator<< (std::ostream &os, const cofe::TensorRank2< Dim, T > &a)
Detailed Description
Continuum Oriented Finite Elements. {}
This namespace contains all the Tensor related facilities.
Author
Jaime Planas & J. M. Sancho.
Function Documentation
template<int N, class T > void cofe::gausselim (T a[N][N], T b[N])
References cofe::CofeUtils::error().
Referenced by cofe::TensorRank2< Dim, T >::solve().
template<int N, class T > void cofe::jacobi (T a[N][N], T d[N], T v[N][N], int & nrot)
References cofe::CofeUtils::error().
template<class T > double cofe::norm (const T & a)
Referenced by lmx::Vector< T >::norm1(), and lmx::Vector< T >::norm2().
template<int Dim, class T > std::ostream& cofe::operator<< (std::ostream & os, const cofe::TensorRank1< Dim, T > & a)
template<int Dim, class T > std::ostream& cofe::operator<< (std::ostream & os, const cofe::TensorRank2< Dim, T > & a)
template<int N, class T > void cofe::rot (T a[N][N], T s, T tau, int i, int j, int k, int l)